import os as _os

DEBUG = False

MALE_NAMES = open("assets/male_names.txt").read().splitlines()
FEMALE_NAMES = open("assets/female_names.txt").read().splitlines()
LAST_NAMES = open("assets/last_names.txt").read().splitlines()

SAVE_PATH = filename = _os.getcwd() + "/game_saves"  # + "/gamedata.pickle"

SALARY_TAX_BRACKETS = [
    [9950, 0.1],
    [40525, 0.12],
    [86375, 0.22],
    [164925, 0.24],
    [209425, 0.32],
    [523600, 0.35],
    0.37,
]

from src.lifesim_lib.translation import _

ILLNESSES_TRANSLATIONS = {
	"Depression": _("Depression"),
	"High Blood Pressure": _("High Blood Pressure"),
}

COMPLIMENTS = [
	_("a bubbly personality"),
	_("a champion"),
	_("a gem"),
	_("a genius"),
	_("a jewel"),
	_("a legend"),
	_("a player"),
	_("a revolutionary"),
	_("a smart cookie"),
	_("a treasure"),
	_("a winner"),
	_("a wizard"),
	_("a visionary"),
	_("adorable"),
	_("admirable"),
	_("an OG"),
	_("brave"),
	_("bright"),
	_("brilliant"),
	_("charming"),
	_("clever"),
	_("cool"),
	_("courageous"),
	_("delightful"),
	_("dope"),
	_("elite"),
	_("fascinating"),
	_("fearless"),
	_("fresh"),
	_("gorgeous"),
	_("golden"),
	_("groovy"),
	_("inspiring"),
	_("intelligent"),
	_("magnificent"),
	_("motivating"),
	_("neat"),
	_("nifty"),
	_("one-of-a-kind"),
	_("a perfect 10"),
	_("phenomenal"),
	_("rad"),
	_("smart"),
	_("spectatular"),
	_("stellar"),
	_("strong"),
	_("stunning"),
	_("stylish"),
	_("swell"),
	_("the best"),
	_("the greatest"),
	_("the life of the party"),
	_("unparalled"),
	_("wise"),
	_("wonderful"),
]

# Insults moved to the bottom


# Conversations section:
# This section is broken into basic conversation depths. It may be useful in future to e.g. not have a heart-to-heart with your {enemy}, {boss}, {whoever}.
# It might also be useful for age / job dependent topics, or to facilitate 'you spoke to your {relation} about which is better {movie} or {movie}' / 'you spoke with your {relation} about {sport} and how {team} will beat {team} this year'

# Casual chats, small-talk, etc. (can take words like 'chatted with your {relation} about' or 'talked about' prior to calling)
CHATS = [
	_("the hierarchy of licorice"),
	_("which is better, Star Wars or Star Trek"),
	_("which is better, Coke or Pepsi"),
	_("which is better, Lord of the Rings or Harry Potter"),
	_("who is better, the Red Sox or Yankees"),
	_("who will win the Monaco Grand Prix"),
	_("how it's illegal to masturbate in Indonesia"),
	_("whether you would rather live without music or television"),
	_("why mannequins have erect nipples"),
	_("Angleina Jolie's lips"),
]
CHATS_CHILD = [
	_("which super power you would most like to have"),
	_("which super power they would most like to have"),
	_("what they want to be when they grow up"),
	_("how much you hate vegetables"),
	_("how scary the toilet is when it gets flushed"),
	_("why the sky is blue"),
	_("where water goes when the toilet gets flushed"),
	_("your favourite movie character"),

]
CHATS_TEEN = [
	_(""),
]
CHATS_ADULT = [
	_(""),
]
CHATS_CLASSMATES_PRIMARY = [
	_(""),
]
CHATS_CLASSMATES_SECONDARY = [
	_(""),
]
CHATS_CLASSMATES_TERTIARY = [
	_(""),
]
CHATS_CO_WORKERS = [
	_(""),
]


# Academic / debatable topics, topics that are contentious etc. (can take words like 'discussed' prior to calling)
DISCUSSIONS = [
	_("why cats are better than dogs"),
	_("why dogs are better than cats"),
	_("the Russia-Ukraine War"),
	_("High Fuel Prices"),
	_("the Metaverse"),
	_("the Economic crisis of Sri Lanka"),
	_("Moonlighting"),
	_("the Pros and Cons of working from home"),
	_("whether people should invest in cryptocurrency"),
	_("the Biomedical waste crisis"),
	_("the impact of 5G on the global economy"),
	_("how to prevent the next pandemic"),
	_("the impact of COVID-19 on the global economy"),
	_("the pros and cons of block chain technology"),
	_("the role of social media in international politics"),
	_("how to end the threat of nuclear war"),
	_("the impact of COVID-19 on the education sector"),
	_("Taliban rule in Afghanistan"),
	_("the rise of the gig economy"),
	_("the harms of passive smoking"),
	_("the advantages and disadvantages of having a credit card"),
	_("whether software should be free for everyone"),
	_("whether gambling should be allowed from the age of 16"),
	_("problems caused by the economic boycott in Cuba"),
	_("how international trade barriers work"),
	_("how the United Nations is based on diplomacy and strengthening relationships"),
	_("whether or not public schools are safe enough"),
	_("whether it is necessary to hold value in what you argue"),
	_("why drink driving is dangerous"),
	_("how India became such a large milk producer"),
	_("how to make money with recycling"),
	_("the decreasing productivity of the Japanese workforce"),
	_("a business model to help health-conscious customers"),
	_("what the best technologies are to safeguard the right of free speech on the internet"),
	_("what the best technologies are to safeguard the right of privacy on the internet"),
	_("how to check for the signs of burnout"),
	_("how to overcome the coal crisis in India"),
	_("the causes of bullying in schools"),
	_("why we should have a minimum wage"),
	_("whether universal basic income is a good idea"),
	_("the leadership changes needed in our country"),
	_("whether empowering women is the solution to violence against women"),
	_("the effects of communalism on social cohesion"),
	_("whether we're becoming too sensitive in society"),
	_("lessons for the world from the COVID-19 pandemic"),
	_("whether crime rates increase because of unemployment"),
	_("causes of poverty around the world"),
	_("the effects of the Internet of Things on our lives"),
	_("whether drug abuse is rampant among teenagers"),
	_("whether anemia effects urban society"),
	_("gender equality in the workplace"),
	_("whether the wealthy should be taxed more"),
	_("whether the poor should be given more assistance"),
	_("whether it is possible to maintain a work-life balance"),
	_("whether saying 'women make good managers' is sexist like saying 'asians are good at maths' is racist"),
	_("whether job creators are needed more than job seekers"),
	_("whether a borderless world is a myth or a reality"),
	_("what would happen if Bitcoin crashed to zero and whether it is possible"),
	_("business ethics in today's market compared with the past and the potential future"),
	_("whether patience is important in business and management"),
	_("whether the family-run business is relevant in today's market"),
	_("whether E-commerce discounts are harmful in the long run and is it the business or customer being harmed"),
	_("whether globalisation is an opportunity or a threat"),
	_("how markets are found and not created"),
	_("whether the world is ready for a cashless society"),
	_("whether physical infrastructure is the answer to social equality"),
	_("whether the public sector being a guarantor of job security is a myth"),
	_("whether a circular economy is key to sustainable development"),
	_("the contribution of the Indian IT industry to the US and global economy"),
	_("whether democracy is a hindrance to economic reforms in India"),
	_("the technology behind Zero Budget Natural Farming"),
	_("the effects of technological change on jobs"),
	_("whether pervasive technology is creating a generation of cyber zombies"),
	_("whether the IT industry will create more or less jobs in the future"),
	_("whether artificial intelligence can replace human intelligence"),
	_("the effects of big data on information privacy"),
	_("whether automation will create more or less jobs"),
	_("the benefits and challenges of data localisation"),
	_("whether artifical intelligence will change the future"),
	_("how technology can be used to tackle financial crimes"),
	_("whether polythene bags should be completely banned"),
	_("how to control air pollution levels"),
	_("whether green jobs are essential for sustainable development"),
	_("how to manage natural disasters"),
	_("how to manage financial disasters"),
	_("methods of disaster recovery"),
	_("the effects of Coronaviruses on the environment"),
	_("whether smart farming is the future of agriculture"),
	_("whether genetic engineering in agriculture is good or bad"),
	_("the effects of climate on the farming system and food supply"),
	_("whether automation in farming is good"),
	_("whether collective farming is a boon or a bane"),
	_("our views on natural versus factory farming"),
	_("our views on conventional farming and organic farming"),
	_("the role of women in agriculture"),
	_("whether agroforestry destroys the environment"),
	_("gay marriage and your views on it"),
	_("whether war is the best option to solve international disputes"),
	_("whether primary school children should be allowed to own mobile phones"),
	_("whether using animals for medical research should be allowed"),
	_("whether men and women will ever be equal, if they already are, and whether equality will last"),
	_("whether you can have a happy family life and a successful career at the same time"),
	_("whether marriage is an outdated institution"),
	_("whether citizens should be allowed to carry guns and other weapons"),
	_("whether the death penalty is acceptable for any reasons"),
	_("whether non-citizens and tourists should be allowed to vote in their country of residence"),
	_("whether sex education should be taught to children under 12"),
	_("whether or not women are paid the same as men"),
	_("whether bribery and corruption is acceptable in government"),
	_("whether bribery and corruption is acceptable in private business"),
	_("whether music that glorifies violence should be banned"),
	_("whether condoms should be distributed for free in primary schools"),
	_("whether nuclear weapons are necessary weapons"),
	_("whether teachers should be allowed to carry guns"),
	_("whether professional sports people earn too much money"),
	_("our views on whether or not beauty contests should be banned"),
	_("our views on whether or not cosmetic surgery should be outlawed"),
	_("our views on whether or not abortions are okay"),
	_("our views on whether or not social deprivation causes crime"),
	_("our views on whether or not military service should be compulsory"),
	_("our views on whether or not war is ever an option for solving international disputes"),
	_("our views on whether or not torture can be acceptable in some cases"),
	_("our views on whether or not curfews keep teens out of trouble"),
	_("our views on whether or not we're becoming too dependent on computers"),
	_("our views on whether or not smoking should be banned worldwide"),
	_("our views on whether or not it should be illegal to ride a bicycle without a helmet"),
	_("our views on whether or not single sex schools are bad for childhood development and lead to unhealthy views of the opposite sex"),
	_("our views on whether or not homework is harmful"),
	_("our views on whether or not the United Nations is a failed organisation"),
	_("our views on whether or not intelligence tests should be given before couples can have children"),
	_("our views on whether or not a woman's place is in the home"),
	_("our views on whether or not it's a man's world"),
	_("our views on whether or not money makes you happy"),
	_("our views on whether or not money can buy you happiness"),
	_("our views on whether or not the internet must be censored to protect society"),
	_("our views on whether or not genetically modified foods have no ill health effects"),
	_("our views on whether a man should have a wife for the family and a paramour for pleasure"),
	_("our views on whether a woman should have a husband for the family and a paramour for pleasure"),
	_("our views on whether soft drugs should be legalised"),
	_("our views on whether or not electric cars help the environment"),
	_("our views on whether or not staying unmarried leads to a happier life"),
	_("our views on whether or not software piracy is a real crime"),
	_("our views on whether or not religion is needed"),
	_("our views on whether veganism is the key to solving climate change"),
	_("our views on whether the police force is institutionally racist"),
	_("our views on whether democracy must be imposed on nations"),
	_("our views on whether the war in Iraq was justified"),
	_("our views on whether your race affects your intelligence"),
	_("our views on whether your race affects your sporting ability"),
	_("our views on whether the world is over populated and steps must be taken to reduce births"),
	_("whether or not euthanasia should be illegal"),
	_("whether or not cloning is a valuable scientific pursuit"),
	_("whether obesity is a disease and not a lifestyle choice"),
	_("whether or not video games contribute to youth violence"),
	_("whether the drinking age should be lowered"),
	_("whether the drinking age should be raised"),
	_("whether the smoking age should be lowered"),
	_("whether the smoking age should be raised"),
	_("whether the age of consent should be lowered"),
	_("whether the age of consent should be raised"),
	_("whether the voting age should be lowered"),
	_("whether the voting age should be raised"),
	_("whether the driving age should be lowered"),
	_("whether the driving age should be raised"),
	_("whether the gambling age should be lowered"),
	_("whether the gambling age should be raised"),
	_("whether the military service age should be lowered"),
	_("whether the military service age should be raised"),
	_("whether drugs should be accepted in sports"),
	_("whether self driving cars are going to make our lives easier"),
	_("whether climate change exists"),
	_("whether carbohydrates are more damaging than fats"),
	_("whether terrorism can be justifed"),
	_("whether or not street prostitution should be illegal"),
	_("whether or not prostitution in a brothel should be illegal"),
	_("whether or not prostituting yourself in your own home should be illegal"),
	_("whether prisoners should be allowed to vote"),
	_("whether prenuptual agreements make families stronger"),
	_("whether corporal punishment should be allowed in schools"),
]
DISCUSSIONS_INFANT = [
	_(""),
]
DISCUSSIONS_CHILD = [
	_("if it is better to scrunch or fold"),
	_("if it is better to squat or sit"),
	_("if it is better to shower or bath"),
	_("if it is better to wipe from the front or back"),
	_("if it is better to "),
	_("your favourite movie character"),
	_("your imaginary friend"),
	
	_("your most prized posession"),
]
DISCUSSIONS_TEEN = [
	_(""),
]
# Important 'life' talks
TALKS = [
	_("not spending enough time with your family"),
]
TALKS_INFANT = [
	_("the importance of not sucking your thumb"),
]
TALKS_CHILD = [
	_("not drawing on the kitchen table"),
]
TALKS_TEEN = [
	_("the importance of cleaning up after yourself"),
]
TALKS_ADULT = [
	_("the importance of saving for retirement")
]

# Emotionally sincere, serious, or personal conversations
HEART_TO_HEARTS = [
	_("the best gift you ever received"),
	_("your most bizarre pet peeves"),
	_("why you love your closest friends"),
	_("your favourite books to read at the beach"),
	_("your favourite foods to eat on a cold night"),
	_("your biggest turn offs in other people"),
	_("remembering the times when you've felt closest together"),
	_("what you would do if you knew you couldn't fail"),
	_("your favourite summertime memory"),
	_("something you've always wanted to try"),
	_("things you've always wanted to try"),
	_("a moment in history you would have liked to have been a part of"),
	_("how to manage money better"),
	_("where you would go if you could time travel"),
	_("what superpower you would have if you could have one"),
	_("what you're feeling thankful for today"),
	_("how much they mean to you"),
	_("something that you know you don't need but you're really grateful you have"),
	_("your fears of not accomplishing your New Year resolutions"),
	_("how silly New Year's resolutions are"),
	_("the best part of your day"),
]
HEART_TO_HEARTS_TEEN = [
	_("what happens when we die"),
]


# Body parts for squabbles, fights etc.
# E.g. 'you squabbled with your {sibling} for not sharing {his_her} candy.' -> 'your {sibling} stormed you! {he_she} ripped your nipple.' 

MALE_BODYPART = [
	_("arm"),
	_("arms"),
	_("left arm"),
	_("right arm"),
	_("leg"),
	_("legs"),
	_("left leg"),
	_("right leg"),
	_("scalp"),
	_("ear"),
	_("ears"),
	_("left ear"),
	_("right ear"),
	_("earlobe"),
	_("earlobes"),
	_("left earlobe"),
	_("right earlobe"),
	_("eye"),
	_("eyes"),
	_("left eye"),
	_("right eye"),
	_("eye socket"),
	_("eye sockets"),
	_("left eye socket"),
	_("right eye socket"),
	_("eyeball"),
	_("eyeballs"),
	_("left eyeball"),
	_("right eyeball"),
	_("eyelid"),
	_("eyelids"),
	_("left eyelid"),
	_("right eyelid"),
	_("eyebrow"),
	_("eyebrows"),
	_("left eyebrow"),
	_("right eyebrow"),
	_("nose"),
	_("nostril"),
	_("nostrils"),
	_("left nostril"),
	_("right nostril"),
	_("cheek"),
	_("cheeks"),
	_("left cheek"),
	_("right cheek"),
	_("lip"),
	_("lips"),
	_("top lip"),
	_("bottom lip"),
	_("philtrum"),
	_("front tooth"),
	_("front teeth"),
	_("tongue"),
	_("jaw"),
	_("chin"),
	_("neck"),
	_("throat"),
	_("jugular"),
	_("trapezius"),
	_("clavicle"),
	_("shoulder"),
	_("shoulders"),
	_("scapula"),
	_("deltoid"),
	_("deltoids"),
	_("delt"),
	_("delts"),
	_("sternum"),
	_("bicep"),
	_("biceps"),
	_("left bicep"),
	_("right bicep"),
	_("tricep"),
	_("triceps"),
	_("left tricep"),
	_("right tricep"),
	_("forearm"),
	_("forearms"),
	_("left forearm"),
	_("right forearm"),
	_("wrist"),
	_("wrists"),
	_("left wrist"),
	_("right wrist"),
	_("ulna"),
	_("ulnas"),
	_("left ulna"),
	_("right ulna"),
	_("hand"),
	_("hands"),
	_("left hand"),
	_("right hand"),
	_("finger"),
	_("fingers"),
	_("left fingers"),
	_("right fingers"),
	_("thumb"),
	_("thumbs"),
	_("left thumb"),
	_("right thumb"),
	_("index finger"),
	_("index fingers"),
	_("left index finger"),
	_("right index finger"),
	_("middle finger"),
	_("middle fingers"),
	_("left middle finger"),
	_("right middle finger"),
	_("rude finger"),
	_("rude fingers"),
	_("left rude finger"),
	_("right rude finger"),
	_("ring finger"),
	_("ring fingers"),
	_("left ring finger"),
	_("right ring finger"),
	_("pinky finger"),
	_("pinky fingers"),
	_("pinky"),
	_("pinkies"),
	_("left pinky"),
	_("right pinky"),
	_("palm"),
	_("palms"),
	_("left palm"),
	_("right palm"),
	_("knuckles"),
	_("left knuckles"),
	_("right knuckles"),
	_("pectoral"),
	_("pectorals"),
	_("left pectoral"),
	_("right pectoral"),
	_("pec"),
	_("pecs"),
	_("left pec"),
	_("right pec"),
	_("nipple"),
	_("nipples"),
	_("left nipple"),
	_("right nipple"),
	_("areola"),
	_("areolas"),
	_("left areola"),
	_("right areola"),
	_("thorax"),
	_("chest"),
	_("breastplate"),
	_("ribs"),
	_("rib"),
	_("left rib"),
	_("left ribs"),
	_("right rib"),
	_("right ribs"),
	_("latissimus"),
	_("lat"),
	_("lats"),
	_("shoulder blade"),
	_("shoulder blades"),
	_("rhomboid"),
	_("rhomboids"),
	_("oblique"),
	_("obliques"),
	_("spine"),
	_("abdominals"),
	_("abs"),
	_("belly"),
	_("belly button"),
	_("navel"),
	_("glute"),
	_("glutes"),
	_("left glute"),
	_("right glute"),
	_("butt cheeks"),
	_("butt cheek"),
	_("left butt cheek"),
	_("right butt cheek"),
	_("anus"),
	_("butt hole"),
	_("bottom"),
	_("rectum"),
	_("coccyx"),
	_("tail bone"),
	_("genitals"),
	_("pubis"),
	_("penis"),
	_("penis shaft"),
	_("shaft"),
	_("testis"),
	_("testicles"),
	_("left testicle"),
	_("right testicle"),
	_("scrotum"),
	_("glans"),
	_("cock"),
	_("willy"),
	_("knob"),
	_("bellend"),
	_("balls"),
	_("left nut"),
	_("right nut"),
	_("nuts"),
	_("epididymis"),
	_("vas defrens"),
	_("left vas defrens"),
	_("right vas defrens"),
	_("foreskin"),
	_("prepuce"),
	_("prostate"),
	_("perineum"),
	_("ball sack"),
	_("anaconda"),
	_("baloney pony"),
	_("chode"),
	_("custard launcher"),
	_("dick"),
	_("ding-dong"),
	_("dipstick"),
	_("disco stick"),
	_("doodle"),
	_("johnson"),
	_("love muscle"),
	_("love stick"),
	_("manhood"),
	_("meat stick"),
	_("old chap"),
	_("one-eyed trouser snake"),
	_("pecker"),
	_("peen"),
	_("pee-pee"),
	_("pickle"),
	_("pink cigar"),
	_("skin flute"),
	_("willie"),
	_("hip"),
	_("hips"),
	_("waist"),
	_("left hip"),
	_("right hip"),
	_("adductor"),
	_("adductors"),
	_("left adductor"),
	_("right adductor"),
	_("abductor"),
	_("abductors"),
	_("left abductor"),
	_("right abductor"),
	_("quadriceps"),
	_("left quadricep"),
	_("right quadricep"),
	_("quads"),
	_("left quad"),
	_("right quad"),
	_("hamstring"),
	_("hamstrings"),
	_("left hamstring"),
	_("right hamstring"),
	_("thigh"),
	_("thighs"),
	_("left thigh"),
	_("right thigh"),
	_("inner thigh"),
	_("inner thighs"),
	_("left inner thigh"),
	_("right inner thigh"),
	_("outer thigh"),
	_("outer thighs"),
	_("left outer thigh"),
	_("right outer thigh"),
	_("knee"),
	_("knees"),
	_("left knee"),
	_("right knee"),
	_("knee cap"),
	_("knee caps"),
	_("left knee cap"),
	_("right knee cap"),
	_("calf"),
	_("left calf"),
	_("right calf"),
	_("calves"),
	_("shin"),
	_("shins"),
	_("left shin"),
	_("right shin"),
	_("ankle"),
	_("ankles"),
	_("left ankle"),
	_("right ankle"),
	_("foot"),
	_("feet"),
	_("left foot"),
	_("right foot"),
	_("toe"),
	_("toes"),
	_("left toes"),
	_("right toes"),
	_("big toe"),
	_("big toes"),
	_("left big toe"),
	_("right big toe"),
	_("index toe"),
	_("index toes"),
	_("left index toe"),
	_("right index toe"),
	_("middle toe"),
	_("middle toes"),
	_("left middle toe"),
	_("right middle toe"),
	_("fourth toe"),
	_("fourth toes"),
	_("left fourth toe"),
	_("right fourth toe"),
	_("little toe"),
	_("little toes"),
	_("left little toe"),
	_("right little toe"),
	_("pinky toe"),
	_("pinky toes"),
	_("left pinky toe"),
	_("right pinky toe"),
]

FEMALE_BODYPART = [
	_("arm"),
	_("arms"),
	_("left arm"),
	_("right arm"),
	_("leg"),
	_("legs"),
	_("left leg"),
	_("right leg"),
	_("scalp"),
	_("ear"),
	_("ears"),
	_("left ear"),
	_("right ear"),
	_("earlobe"),
	_("earlobes"),
	_("left earlobe"),
	_("right earlobe"),
	_("eye"),
	_("eyes"),
	_("left eye"),
	_("right eye"),
	_("eye socket"),
	_("eye sockets"),
	_("left eye socket"),
	_("right eye socket"),
	_("eyeball"),
	_("eyeballs"),
	_("left eyeball"),
	_("right eyeball"),
	_("eyelid"),
	_("eyelids"),
	_("left eyelid"),
	_("right eyelid"),
	_("eyebrow"),
	_("eyebrows"),
	_("left eyebrow"),
	_("right eyebrow"),
	_("nose"),
	_("nostril"),
	_("nostrils"),
	_("left nostril"),
	_("right nostril"),
	_("cheek"),
	_("cheeks"),
	_("left cheek"),
	_("right cheek"),
	_("lip"),
	_("lips"),
	_("top lip"),
	_("bottom lip"),
	_("philtrum"),
	_("front tooth"),
	_("front teeth"),
	_("tongue"),
	_("jaw"),
	_("chin"),
	_("neck"),
	_("throat"),
	_("jugular"),
	_("trapezius"),
	_("clavicle"),
	_("shoulder"),
	_("shoulders"),
	_("scapula"),
	_("deltoid"),
	_("deltoids"),
	_("delt"),
	_("delts"),
	_("sternum"),
	_("bicep"),
	_("biceps"),
	_("left bicep"),
	_("right bicep"),
	_("tricep"),
	_("triceps"),
	_("left tricep"),
	_("right tricep"),
	_("forearm"),
	_("forearms"),
	_("left forearm"),
	_("right forearm"),
	_("wrist"),
	_("wrists"),
	_("left wrist"),
	_("right wrist"),
	_("ulna"),
	_("ulnas"),
	_("left ulna"),
	_("right ulna"),
	_("hand"),
	_("hands"),
	_("left hand"),
	_("right hand"),
	_("finger"),
	_("fingers"),
	_("left fingers"),
	_("right fingers"),
	_("thumb"),
	_("thumbs"),
	_("left thumb"),
	_("right thumb"),
	_("index finger"),
	_("index fingers"),
	_("left index finger"),
	_("right index finger"),
	_("middle finger"),
	_("middle fingers"),
	_("left middle finger"),
	_("right middle finger"),
	_("rude finger"),
	_("rude fingers"),
	_("left rude finger"),
	_("right rude finger"),
	_("ring finger"),
	_("ring fingers"),
	_("left ring finger"),
	_("right ring finger"),
	_("pinky finger"),
	_("pinky fingers"),
	_("pinky"),
	_("pinkies"),
	_("left pinky"),
	_("right pinky"),
	_("palm"),
	_("palms"),
	_("left palm"),
	_("right palm"),
	_("knuckles"),
	_("left knuckles"),
	_("right knuckles"),
	_("pectoral"),
	_("pectorals"),
	_("left pectoral"),
	_("right pectoral"),
	_("breast"),
	_("breasts"),
	_("left breast"),
	_("right breast"),
	_("boob"),
	_("boobs"),
	_("left boob"),
	_("right boob"),
	_("tit"),
	_("tits"),
	_("left tit"),
	_("right tit"),
	_("nipple"),
	_("nipples"),
	_("left nipple"),
	_("right nipple"),
	_("areola"),
	_("areolas"),
	_("left areola"),
	_("right areola"),
	_("thorax"),
	_("chest"),
	_("breastplate"),
	_("ribs"),
	_("rib"),
	_("left rib"),
	_("left ribs"),
	_("right rib"),
	_("right ribs"),
	_("latissimus"),
	_("lat"),
	_("lats"),
	_("shoulder blade"),
	_("shoulder blades"),
	_("rhomboid"),
	_("rhomboids"),
	_("oblique"),
	_("obliques"),
	_("spine"),
	_("abdominals"),
	_("abs"),
	_("belly"),
	_("belly button"),
	_("navel"),
	_("glute"),
	_("glutes"),
	_("left glute"),
	_("right glute"),
	_("butt cheeks"),
	_("butt cheek"),
	_("left butt cheek"),
	_("right butt cheek"),
	_("anus"),
	_("butt hole"),
	_("bottom"),
	_("rectum"),
	_("coccyx"),
	_("tail bone"),
	_("genitals"),
	_("pubis"),
	_("mons pubis"),
	_("pubic mound"),
	_("mons"),
	_("vagina"),
	_("labia"),
	_("labia majora"),
	_("left labium majus"),
	_("right labium majus"),
	_("labia minora"),
	_("labium minus"),
	_("left labium minus"),
	_("right labium minus"),
	_("pudendal cleft"),
	_("clitoris"),
	_("clitoral hood"),
	_("clitoral glans"),
	_("urinary meatus"),
	_("meatus"),
	_("vaginal orifice"),
	_("vulva"),
	_("ovary"),
	_("ovaries"),
	_("left ovary"),
	_("right ovary"),
	_("pussy"),
	_("cervix"),
	_("left pussy lip"),
	_("right pussy lip"),
	_("pussy lips"),
	_("urethra"),
	_("hymen"),
	_("fanny"),
	_("skene's gland"),
	_("perineum"),
	_("clit"),
	_("g-spot"),
	_("panty hamster"),
	_("mossy cleft"),
	_("pink taco"),
	_("snatch"),
	_("twat"),
	_("hoo hoo"),
	_("foo foo"),
	_("poon"),
	_("poony"),
	_("lady garden"),
	_("vajayjay"),
	_("vag"),
	_("hot box"),
	_("love tunnel"),
	_("honey pot"),
	_("nether regions"),
	_("lady parts"),
	_("girly bits"),
	_("flower"),
	_("cookie"),
	_("hip"),
	_("hips"),
	_("waist"),
	_("left hip"),
	_("right hip"),
	_("adductor"),
	_("adductors"),
	_("left adductor"),
	_("right adductor"),
	_("abductor"),
	_("abductors"),
	_("left abductor"),
	_("right abductor"),
	_("quadriceps"),
	_("left quadricep"),
	_("right quadricep"),
	_("quads"),
	_("left quad"),
	_("right quad"),
	_("hamstring"),
	_("hamstrings"),
	_("left hamstring"),
	_("right hamstring"),
	_("thigh"),
	_("thighs"),
	_("left thigh"),
	_("right thigh"),
	_("inner thigh"),
	_("inner thighs"),
	_("left inner thigh"),
	_("right inner thigh"),
	_("outer thigh"),
	_("outer thighs"),
	_("left outer thigh"),
	_("right outer thigh"),
	_("knee"),
	_("knees"),
	_("left knee"),
	_("right knee"),
	_("knee cap"),
	_("knee caps"),
	_("left knee cap"),
	_("right knee cap"),
	_("calf"),
	_("left calf"),
	_("right calf"),
	_("calves"),
	_("shin"),
	_("shins"),
	_("left shin"),
	_("right shin"),
	_("ankle"),
	_("ankles"),
	_("left ankle"),
	_("right ankle"),
	_("foot"),
	_("feet"),
	_("left foot"),
	_("right foot"),
	_("toe"),
	_("toes"),
	_("left toes"),
	_("right toes"),
	_("big toe"),
	_("big toes"),
	_("left big toe"),
	_("right big toe"),
	_("index toe"),
	_("index toes"),
	_("left index toe"),
	_("right index toe"),
	_("middle toe"),
	_("middle toes"),
	_("left middle toe"),
	_("right middle toe"),
	_("fourth toe"),
	_("fourth toes"),
	_("left fourth toe"),
	_("right fourth toe"),
	_("little toe"),
	_("little toes"),
	_("left little toe"),
	_("right little toe"),
	_("pinky toe"),
	_("pinky toes"),
	_("left pinky toe"),
	_("right pinky toe"),
]

# Fighting words
# Same gist as above, e.g. for when you get attacked in a park and someone gouges your belly button or bites your pinky toe

ATTACK_WORD = [
	_("punched"),
	_("hit"),
	_("kicked"),
	_("attacked"),
	_("bit"),
	_("head butted"),
	_("kneed"),
	_("elbowed"),
	_("jabbed"),
	_("stabbed"),
	_("whacked"),
	_("slapped"),
	_("back-handed"),
	_("booted"),
	_("smacked"),
	_("karate chopped"),
	_("judo chopped"),
	_("beat"),
	_("bashed"),
	_("smashed"),
	_("body slammed"),
	_("slammed"),
	_("kung fu kicked"),
	_("shadow kicked"),
	_("kickboxed"),
	_("boxed"),
	_("clawed"),
	_("one inch punched"),
	_("pounded"),
	_("pinched"),
	_("flicked"),
	_("flying kicked"),
	_("gouged"),
	_("arm barred"),
	_("axe kicked"),
	_("back controlled"),
	_("backstabbed"),
	_("barrel rolled"),
	_("battering rammed"),
	_("body locked"),
	_("choked"),
	_("chokeslammed"),
	_("chopping blocked"),
	_("clinched"),
	_("cobra striked"),
	_("crossed"),
	_("crucified"),
	_("crushed"),
	_("counter attacked"),
	_("curb stomped"),
	_("dirty boxed"),
	_("elbow striked"),
	_("elbow struck"),
	_("elbow slammed"),
	_("fisted"),
	_("face-slammed"),
	_("full body power-bombed"),
	_("gorilla swung"),
	_("grounded and pounded"),
	_("grizzly-bear death-choked"),
	_("guarded"),
	_("guillotined"),
	_("gut busted"),
	_("hammerfisted"),
	_("hooked"),
	_("jawlocked"),
	_("knuckle busted"),
	_("leg kicked"),
	_("leg locked"),
	_("mounted"),
	_("preemptively struck"),
	_("piledrived"),
	_("rear naked choke held"),
	_("rhino charged"),
	_("round-housed"),
	_("side controlled"),
	_("skull crushed"),
	_("speared"),
	_("spinning back-fisted"),
	_("spinning back-kicked"),
	_("sprawled"),
	_("stormed"),
	_("stubborn-mule leg-kicked"),
	_("superkicked"),
	_("supermanned"),
	_("superman punched"),
	_("sweeped"),
	_("swept"),
	_("sweep kicked"),
	_("T-boned"),
	_("takedowned"),
	_("thunderbolt knee-dived"),
	_("tiger-claw back-chopped"),
	_("tight-grip headlocked"),
	_("took-down"),
	_("tombstoned"),
	_("tapped out"),
	_("triangled"),
	_("triangle choked"),
	_("uppercutted"),
]


# Celebrity list
# For use in situations like '{celebrity} followed you on instagram'; or "you were talking with your {relation} about {adam brody}'s {left ankle}"; "while you were working at {chicken shop} you noticed {seth rogan} stuck in traffic outside. You waved, {he} didn't wave back." etc
# Rough alphabetical order only so far

CELEBRITY_MALE_ACTOR = [
	_("Alex Pettyfer"),
	_("Ashton Kutcher"),
	_("Adam Brody"),
	_("Andrew Garfield"),
	_("Alexander Skarsgård"),
	_("Austin Nichols"),
	_("Allan Hyde"),
	_("Adam Garcia"),
	_("Arnold Schwarzenegger"),
	_("Ben McKenzie"),
	_("Bryan Greenberg"),
	_("Brad Pitt"),
	_("Bradley Cooper"),
	_("Channing Tatum"),
	_("Clive Owen"),
	_("Chace Crawford"),
	_("Cam Gigandet"),
	_("Chris Brown"),
	_("Chris Pine"),
	_("Chad Michael Murray"),
	_("Columbus Short"),
	_("Christian Bale"),
	_("Casey Affleck"),
	_("Cillian Murphy"),
	_("Daniel Craig"),
	_("David Beckham"),
	_("Ed Westwick"),
	_("Eric Bana"),
	_("Emile Hirsch"),
	_("Eric Dane"),
	_("Gerard Butler"),
	_("Garrett Hedlund"),
	_("Hayden Christensen"),
	_("Hugh Jackman"),
	_("Hugh Laurie"),
	_("Hugh Dancy"),
	_("Heath Ledger"),
	_("Ian Somerhalder"),
	_("James Lafferty"),
	_("James Marsden"),
	_("John Mayer"),
	_("Jude Law"),
	_("Jensen Ackles"),
	_("Jake Gyllenhaal"),
	_("Justin Chambers"),
	_("Jesse Metcalfe"),
	_("Justin Timberlake"),
	_("Javier Bardem"),
	_("Joe Manganiello"),
	_("Johnny Depp"),
	_("James Franco"),
	_("Jack O'Connell"),
	_("Kellan Lutz"),
	_("Josh Hartnett"),
	_("Jason Segel"),
	_("Jared Padalecki"),
	_("Joseph Gordon-Levitt"),
	_("Liam Hemsworth"),
	_("Leonardo DiCaprio"),
	_("Luke Pasqualino"),
	_("Milo Ventimiglia"),
	_("Mark Salling"),
	_("Matthew Goode"),
	_("Mads Mikkelsen"),
	_("Marshall Mathers"),
	_("Mekhi Phifer"),
	_("Matt Lanter"),
	_("Mike Vogel"),
	_("Nick Zano"),
	_("Orlando Bloom"),
	_("Patrick Swayze"),
	_("Penn Badgley"),
	_("Peter Facinelli"),
	_("Paul Walker"),
	_("Ryan Gosling"),
	_("Ryan Reynolds"),
	_("Robbie Jones"),
	_("Robert Pattinson"),
	_("Rick Malambri"),
	_("Ryan Kwanten"),
	_("Ryan Phillippe"),
	_("Rafi Gavron"),
	_("Sam Worthington"),
	_("Sean Faris"),
	_("Sylvester Stallone"),
	_("Seth Rogan"),
	_("Shia LaBeouf"),
	_("Stephen Colletti"),
	_("Shane West"),
	_("Simon Rex"),
	_("Taylor Lautner"),
	_("Tom Hardy"),
	_("Tupac Shakur"),
	_("Tristan Mack Wilds"),
	_("Timothy Olyphant"),
	_("Tom Welling"),
	_("Travis Barker"),
	_("Wentworth Miller"),
	_("Zac Efron"),
]
CELEBRITY_MALE_ATHLETE = [
	_("Arnold Schwarzenegger"),
	_("David Beckham"),
]
CELEBRITY_MALE_AUTHOR = [
	_("Joe Manganiello"),
]
CELEBRITY_MALE_BUSINESS = [
	_("Elon Musk"),
]
CELEBRITY_MALE_DANCER = [
	_("Justin Timberlake"),
]
CELEBRITY_MALE_DIRECTOR = [
	_("Joe Manganiello"),
]
CELEBRITY_MALE_FASHION_DESIGNER = [
	_("Michael Kors"),
	_("Tom Ford"),
]
CELEBRITY_MALE_MODEL = [
	_("David Gandy"),
	_("Sean O'Pry"),
]
CELEBRITY_MALE_MUSICIAN = [		
	_("Eminem"),
	_("Jared Followill"),
	_("John Mayer"),
	_("Justin Timberlake"),
	_("Tupac Shakur"),
]
CELEBRITY_MALE_POLITICIAN = [
	_("Arnold Schwarzenegger"),
]
CELEBRITY_MALE_PORNSTAR = [
	_("James Deen"),
]
CELEBRITY_MALE_PRODUCER = [
	_("Arnold Schwarzenegger"),
	_("Brad Pitt"),
	_("Joe Manganiello"),
]
CELEBRITY_MALE_ROYAL = [
	_("Prince Carl Philip of Sweden, Duke of Värmland"),
]
CELBRITY_MALE_SCREENWRITER = [
	_("Sylvester Stallone"),
	_("Seth Rogan"),
]
CELEBRITY_MALE_SELF = [
	_("Arnold Schwarzenegger"),
]
CELEBRITY_MALE_SOCIAL_MEDIA = [
	_("Zach King"),
]
CELEBRITY_MALE_WRESTLER = [
	_("Randy Orton"),
]
CELEBRITY_MALE_WRITER = [
	_("Stan Lee"),
]

CELEBRITY_FEMALE_ACTOR = [
	_("Adriana Lima"),
	_("Aishwarya Rai Bachchan"),
	_("Alessandra Ambrosio"),
	_("Amber Heard"),
	_("Ana Beatriz Barros"),
	_("Anna Paquin"),
	_("AnnaSophia Robb"),
	_("Anne Vyalitsyna"),
	_("Angelina Jolie"),
	_("Ashley Benson"),
	_("Ashley Greene"),
	_("Bar Refaeli"),
	_("Behati Prinsloo"),
	_("Beyoncé Knowles"),
	_("Blake Lively"),
	_("Brooklyn Decker"),
	_("Candice Swanepoel"),
	_("Cassie Ventura"),
	_("Charlize Theron"),
	_("Cheryl Cole"),
	_("Chloë Grace Moretz"),
	_("Cindy Crawford"),
	_("Demi Lovato"),
	_("Denise Richards"),
	_("Diane Kruger"),
	_("Doutzen Kroes"),
	_("Elisha Cuthbert"),
	_("Emilia Clarke"),
	_("Emily Blunt"),
	_("Emma Stone"),
	_("Emma Watson"),
	_("Erin Heatherton"),
	_("Eva Green"),
	_("Eva Longoria"),
	_("Eva Mendes"),
	_("Freida Pinto"),
	_("Gisele Bündchen"),
	_("Hilary Duff"),
	_("Indiana Evans"),
	_("Irina Shayk"),
	_("Isabel Lucas"),
	_("Izabel Goulart"),
	_("Jenna Dewan"),
	_("Jennifer Lawrence"),
	_("Jessica Alba"),
	_("Jessica Biel"),
	_("Jordana Brewster"),
	_("Josie Maran"),
	_("Karolina Kurkova"),
	_("Kate Beckinsale"),
	_("Kate Upton"),
	_("Katie Holmes"),
	_("Keira Knightley"),
	_("Kelly Brook"),
	_("Kendall Jenner"),
	_("Kim Kardashian"),
	_("Kristen Stewart"),
	_("Kristin Kreuk"),
	_("Laetitia Casta"),
	_("Lauren Conrad"),
	_("Lily Aldridge"),
	_("Lucy Hale"),
	_("Marion Cotillard"),
	_("Nikki Reed"),
	_("Nina Dobrev"),
	_("Olivia Wilde"),
	_("Malin Akerman"),
	_("Marisa Miller"),
	_("Megan Fox"),
	_("Minka Kelly"),
	_("Mila Kunis"),
	_("Miranda Kerr"),
	_("Monica Bellucci"),
	_("Natalia Vodianova"),
	_("Natalie Portman"),
	_("Nicole Scherzinger"),
	_("Olivia Culpo"),
	_("Penélope Cruz"),
	_("Rachel Bilson"),
	_("Rachel McAdams"),
	_("Rachael Taylor"),
	_("Rachel Weisz"),
	_("Rihanna Fenty"),
	_("Roselyn Sanchez"),
	_("Rosie Huntington-Whiteley"),
	_("Salma Hayek"),
	_("Sara Carbonero"),
	_("Scarlett Johansson"),
	_("Selena Gomez"),
	_("Shanina Shaik"),
	_("Shay Mitchell"),
	_("Sienna Miller"),
	_("Sofía Vergara"),
	_("Stacy Keibler"),
	_("Tyra Banks"),
	_("Vanessa Hudgens"),
	_("Ximena Navarrete"),
	_("Zoe Saldana"),
]
CELEBRITY_FEMALE_ATHLETE = [
	_("Serena Williams"),
]
CELEBRITY_FEMALE_BUSINESS = [
	_("Sofía Vergara"),
]
CELEBRITY_FEMALE_CHEERLEADER = [
	_("Demi Lovato"),
	_("Stacy Keibler"),
]
CELEBRITY_FEMALE_DANCER = [
	_("Ashley Benson"),
	_("Cassie Ventura"),
	_("Jenna Dewan"),
	_("Roselyn Sanchez"),
	_("Stacy Keibler"),
]
CELEBRITY_FEMALE_FASHION_DESIGNER = [
	_("Kim Kardashian"),
	_("Rihanna Fenty"),
]
CELEBRITY_FEMALE_MODEL = [
	_("Adriana Lima"),
	_("Aishwarya Rai Bachchan"),
	_("Alessandra Ambrosio"),
	_("Ana Beatriz Barros"),
	_("Anne Vyalitsyna"),
	_("Bar Refaeli"),
	_("Behati Prinsloo"),
	_("Brooklyn Decker"),
	_("Candice Swanepoel"),
	_("Cassie Ventura"),
	_("Cindy Crawford"),
	_("Denise Richards"),
	_("Doutzen Kroes"),
	_("Elisha Cuthbert"),
	_("Eva Green"),
	_("Gisele Bündchen"),
	_("Irina Shayk"),
	_("Izabel Goulart"),
	_("Jenna Dewan"),
	_("Josie Maran"),
	_("Karolina Kurkova"),
	_("Kate Upton"),
	_("Kelly Brook"),
	_("Kendall Jenner"),
	_("Laetitia Casta"),
	_("Lily Aldridge"),
	_("Malin Akerman"),
	_("Marisa Miller"),
	_("Miranda Kerr"),
	_("Monica Bellucci"),
	_("Natalia Vodianova"),
	_("Olivia Culpo"),
	_("Rachael Taylor"),
	_("Roselyn Sanchez"),
	_("Rosie Huntington-Whiteley"),
	_("Shay Mitchell"),
	_("Sienna Miller"),
	_("Sofía Vergara"),
	_("Stacy Keibler"),
	_("Tyra Banks"),
	_("Ximena Navarrete"),
]
CELEBRITY_FEMALE_MUSICIAN = [
	_("Ashley Benson"),
	_("Beyoncé Knowles"),
	_("Cassie Ventura"),
	_("Cheryl Cole"),
	_("Demi Lovato"),
	_("Indiana Evans"),
	_("Minka Kelly"),
	_("Rihanna Fenty"),
	_("Roselyn Sanchez"),
	_("Selena Gomez"),
]
CELEBRITY_FEMALE_POLITICIAN = [
	_("Hillary Clinton"),
]
CELEBRITY_FEMALE_PORNSTAR = [
	_("Jenna Jameson"),
]
CELEBRITY_FEMALE_PRODUCER = [
	_("Charlize Theron"),
	_("Cindy Crawford"),
	_("Marion Cotillard"),
	_("Roselyn Sanchez"),
	_("Selena Gomez"),
	_("Tyra Banks"),
]
CELEBRITY_FEMALE_ROYAL = [
	_("Catherine Middleton, Princess of Wales"),
]
CELBRITY_FEMALE_SCREENWRITER = [
	_("Nikki Reed"),
]
CELEBRITY_FEMALE_SELF = [
	_("Catherine Middleton, Princess of Wales"),
	_("Natalia Vodianova"),
	_("Pippa Middleton"),
]
CELEBRITY_FEMALE_SOCIAL_MEDIA = [
	_("Olivia Culpo"),
]
CELEBRITY_FEMALE_WRESTLER = [
	_("Stacy Keibler"),
]
CELEBRITY_FEMALE_WRITER = [
	_("Kim Kardashian"),
	_("Roselyn Sanchez"),
	_("Shay Mitchell"),
	_("Tyra Banks"),
]


# List of Urban locations (a park, a bank etc.)

URBAN_LOCATION = [
	_("an airport"),
	_("an airfield"),
	_("an alleyway"),
	_("an ambulance station"),
	_("an apartment building"),
	_("an aquarium"),
	_("an arcade"),
	_("an art gallery"),
	_("an avenue"),
	_("a bakery"),
	_("a bank"),
	_("a bar"),
	_("a barber shop"),
	_("a beauty salon"),
	_("a bed & breakfast"),
	_("a bicycle rental stand"),
	_("a billboard"),
	_("a bookstore"),
	_("a boulevard"),
	_("a bowling alley"),
	_("a bridge"),
	_("a bus stop"),
	_("a butcher's shop"),
	_("a cafe"),
	_("a canal"),
	_("a church"),
	_("City Hall"),
	_("a clinic"),
	_("a coffee shop"),
	_("a college"),
	_("a community centre"),
	_("a community gardens"),
	_("a concert hall"),
	_("a condominium"),
	_("a construction site"),
	_("a convenience store"),
	_("a court"),
	_("a cycle highway"),
	_("a daycare centre"),
	_("a dentist"),
	_("a department store"),
	_("a dock"),
	_("the docks"),
	_("a doctor's office"),
	_("some drainage infrastructure"),
	_("a dry cleaner"),
	_("an embassy"),
	_("a factory"),
	_("a fire hydrant"),
	_("a fire station"),
	_("a flower shop"),
	_("a garbage facility"),
	_("a garden"),
	_("a gardens"),
	_("a government building"),
	_("a green-roof"),
	_("a grocery store"),
	_("a greengrocer"),
	_("a gym"),
	_("a gymnasium"),
	_("a harbour"),
	_("the harbour"),
	_("a highway"),
	_("a historical building"),
	_("a historical site"),
	_("a hospital"),
	_("a hotel"),
	_("a house"),
	_("a jail"),
	_("a karaoke bar"),
	_("a karaoke lounge"),
	_("a landmark"),
	_("a laundromat"),
	_("a library"),
	_("a linear park"),
	_("a market"),
	_("the markets"),
	_("a mixed-use building"),
	_("a mixed-use street"),
	_("a monument"),
	_("a movie theatre"),
	_("a museum"),
	_("a nature reserve"),
	_("a newspaper office"),
	_("some night architecture"),
	_("a nightclub"),
	_("a nursery school"),
	_("a nursing home"),
	_("an observatory"),
	_("an office building"),
	_("an opera house"),
	_("some outdoor seating"),
	_("a park"),
	_("a patisserie"),
	_("some pedestrian infrastructure"),
	_("a performance theatre"),
	_("a pharmacist"),
	_("a place of worship"),
	_("a play street"),
	_("a playground"),
	_("a police station"),
	_("a port"),
	_("the port"),
	_("a post office"),
	_("a prison"),
	_("a product showroom"),
	_("a pub"),
	_("a public bath"),
	_("a public pool"),
	_("a public square"),
	_("a public toilet"),
	_("a radio station"),
	_("a recreation centre"),
	_("a recreation facility"),
	_("some remarkable architecture"),
	_("a restaurant"),
	_("a river"),
	_("a school"),
	_("the sewers"),
	_("a shopping centre"),
	_("a shopping mall"),
	_("a shop"),
	_("a skating rink"),
	_("a skyscraper"),
	_("a spa"),
	_("a sports facility"),
	_("a sports shop"),
	_("a sports stadium"),
	_("a sports store"),
	_("a stadium"),
	_("a stream"),
	_("a street"),
	_("some street art"),
	_("a street food vendor"),
	_("a street vendor"),
	_("a street light"),
	_("some street lights"),
	_("a strip of shops"),
	_("a subway station"),
	_("a swimming pool"),
	_("a taxi stand"),
	_("a technology centre"),
	_("some tech infrastructure"),
	_("a television station"),
	_("a tennis court"),
	
	_("a temple"),
	_("a synagogue"),
	_(""),
]

# List of Natural locations (a mountain, a forest etc.)

NATURAL_LOCATION = [

]

# List of Environmental locations. E.g. 'You practiced writing a story, you chose comic sans and began with "It was {a dark and stormy night}', or "You {beat the meat} while thinking of {margaret thatcher} on {a hot sunny day}"

ENVIRONMENTAL_LOCATION = [

]


# Insults: does what it says on the box. opposite list of compliments. (can be premised with 'called you {insults}')
INSULTS = [
	_("an abomination"),
	_("absolute zero"),
	_("an absolute zero"),
	_("an accident"),
	_("an acrotomophile"),
	_("addle-brained"),
	_("addle headed"),
	_("an airhead"),
	_("an alcatote"),
	_("an animal"),
	_("an animal fucker"),
	_("an anus licker"),
	_("an ape"),
	_("an ape fingerer"),
	_("an ape fondler"),
	_("an ape fucker"),
	_("an ape groper"),
	_("an ape humper"),
	_("an ape molester"),
	_("an ape porker"),
	_("an ape ravisher"),
	_("an ape rooter"),
	_("an ape screwer"),
	_("an ape shafter"),
	_("an ape shagger"),
	_("an ape snogger"),
	_("an arse"),
	_("an arsebadger"),
	_("arsebreath"),
	_("arseface"),
	_("an arsehole"),
	_("an arsewipe"),
	_("an ass"),
	_("an assaholic"),
	_("an assbag"),
	_("an ass bitch"),
	_("an ass clown"),
	_("an asscunt"),
	_("an assface"),
	_("an assfucker"),
	_("an asshat"),
	_("an asshole"),
	_("ass-kisser"),
	_("an ass-kisser"),
	_("an ass master"),
	_("an assmonkey"),
	_("an assmouth"),
	_("an assmunch"),
	_("an ass-nugget"),
	_("an ass rammer"),
	_("an ass suckker"),
	_("an asstard"),
	_("an assweed"),
	_("an asswipe"),
	_("an aunt boffer"),
	_("an aunt bonker"),
	_("an aunt fingerer"),
	_("an aunt fondler"),
	_("an aunt fucker"),
	_("an aunt groper"),
	_("an aunt humper"),
	_("an aunt molester"),
	_("an aunt pasher"),
	_("an aunt porker"),
	_("an aunt ravisher"),
	_("an aunt rooter"),
	_("an aunt screwer"),
	_("an aunt seducer"),
	_("an aunt shafter"),
	_("an aunt shagger"),
	_("an aunt snogger"),
	_("a baboon"),
	_("a baby butcher"),
	_("a backstabber"),
	_("a backwoodsman"),
	_("a badger fingerer"),
	_("a badger fondler"),
	_("a badger fucker"),
	_("a badger groper"),
	_("a badger humper"),
	_("a badger molester"),
	_("a badger porker"),
	_("a badger ravisher"),
	_("a badger rooter"),
	_("a badger screwer"),
	_("a badger shafter"),
	_("a badger shagger"),
	_("a badger snogger"),
	_("a bad nut"),
	_("a bag of dicks"),
	_("a bag whore"),
	_("a ball kicker"),
	_("a ball licker"),
	_("a balloon head"),
	_("a ballsack"),
	_("a barbarian"),
	_("a barbie-fucker"),
	_("a barnacle head"),
	_("a bashful Beethoven"),
	_("a bastard"),
	_("a bean head"),
	_("a beast of burden"),
	_("a beaver"),
	_("a Becky"),
	_("a bedwetter"),
	_("a beetle head"),
	_("a beggar"),
	_("a beginner"),
	_("a belch"),
	_("a bellend"),
	_("a bell-end"),
	_("a belly button"),
	_("a berk"),
	_("a beta"),
	_("a beta cuck"),
	_("a biatch"),
	_("a big brother fingerer"),
	_("a big brother fondler"),
	_("a big brother fucker"),
	_("a big brother groper"),
	_("a big brother humper"),
	_("a big brother molester"),
	_("a big brother pasher"),
	_("a big brother porker"),
	_("a big brother ravisher"),
	_("a big brother rooter"),
	_("a big brother screwer"),
	_("a big brother seducer"),
	_("a big brother shafter"),
	_("a big brother shagger"),
	_("a big brother snogger"),
	_("a big sister fingerer"),
	_("a big sister fister"),
	_("a big sister fondler"),
	_("a big sister fucker"),
	_("a big sister groper"),
	_("a big sister humper"),
	_("a big sister molester"),
	_("a big sister pasher"),
	_("a big sister porker"),
	_("a big sister ravisher"),
	_("a big sister rooter"),
	_("a big sister screwer"),
	_("a big sister seducer"),
	_("a big sister shafter"),
	_("a big sister shagger"),
	_("a big sister snogger"),
	_("a bimbo"),
	_("a bird brain"),
	_("a bird fingerer"),
	_("a bird fondler"),
	_("a bird fucker"),
	_("a bird groper"),
	_("a bird humper"),
	_("a bird molester"),
	_("a bird porker"),
	_("a bird ravisher"),
	_("a bird rooter"),
	_("a bird screwer"),
	_("a bird shafter"),
	_("a bird shagger"),
	_("a bird snogger"),
	_("bitch-tits"),
	_("bitch tits"),
	_("a bitchwad"),
	_("a bitchwhore"),
	_("a bitchzilla"),
	_("a biter"),
	_("a biznatch"),
	_("a blabbermouth"),
	_("a blaggard"),
	_("a blockhead"),
	_("a blubber butt"),
	_("a blubber gut"),
	_("a body shamer"),
	_("a body snatcher"),
	_("a bonehead"),
	_("a boob"),
	_("booby turds"),
	_("a booger"),
	_("a boomer"),
	_("a bootlicker"),
	_("a boozer"),
	_("a bot"),
	_("a box of dildos"),
	_("a boy boffer"),
	_("a boy bonker"),
	_("a boy fingerer"),
	_("a boy fondler"),
	_("a boy fucker"),
	_("a boy groper"),
	_("a boy humper"),
	_("a boy molester"),
	_("a boy pasher"),
	_("a boy porker"),
	_("a boy ravisher"),
	_("a boy rooter"),
	_("a boy screwer"),
	_("a boy seducer"),
	_("a boy shafter"),
	_("a boy shagger"),
	_("a boy snogger"),
	_("a bozo"),
	_("a brainlet"),
	_("a brat"),
	_("bratfaced"),
	_("a bratface"),
	_("a bread and butter boy"),
	_("a brick fucker"),
	_("a brickhead"),
	_("a brother fingerer"),
	_("a brother fondler"),
	_("a brother fucker"),
	_("a brother groper"),
	_("a brother humper"),
	_("a brother molester"),
	_("a brother pasher"),
	_("a brother porker"),
	_("a brother ravisher"),
	_("a brother rooter"),
	_("a brother screwer"),
	_("a brother seducer"),
	_("a brother shafter"),
	_("a brother shagger"),
	_("a brother snogger"),
	_("a brown nose"),
	_("a brown-nose"),
	_("a brown-noser"),
	_("a bubbler"),
	_("a buffoon"),
	_("a bug fucker"),
	_("a bugger"),
	_("a buggerer"),
	_("a bull dyke"),
	_("a bull fucker"),
	_("a bully"),
	_("a bum"),
	_("a bum chum"),
	_("a bum fucker"),
	_("a bunghole"),
	_("a bungholio"),
	_("a bungleberry"),
	_("a burden"),
	_("a burden on society"),
	_("a butt"),
	_("buttbreath"),
	_("a butter-head"),
	_("a buttface"),
	_("a butthole"),
	_("a butt fucker"),
	_("a butt-head"),
	_("a butt-hole"),
	_("a butt kisser"),
	_("a butt knuckler"),
	_("a butt licker"),
	_("a butt-lord"),
	_("a butt-munch"),
	_("a butt muncher"),
	_("a butt nugget"),
	_("a butt pirate"),
	_("a butt sniffer"),
	_("a butt tickler"),
	_("a buttwad"),
	_("a butt-wipe"),
	_("a cactus fucker"),
	_("a calf fingerer"),
	_("a calf fondler"),
	_("a calf fucker"),
	_("a calf groper"),
	_("a calf humper"),
	_("a calf molester"),
	_("a calf porker"),
	_("a calf ravisher"),
	_("a calf rooter"),
	_("a calf screwer"),
	_("a calf shafter"),
	_("a calf shagger"),
	_("a calf snogger"),
	_("a camel fingerer"),
	_("a camel fondler"),
	_("a camel fucker"),
	_("a camel groper"),
	_("a camel humper"),
	_("a camel molester"),
	_("a camel porker"),
	_("a camel ravisher"),
	_("a camel rooter"),
	_("a camel screwer"),
	_("a camel shafter"),
	_("a camel shagger"),
	_("a camel snogger"),
	_("a cannibal"),
	_("a carny"),
	_("a carpet muncher"),
	_("a cat fingerer"),
	_("a cat fondler"),
	_("a cat fucker"),
	_("a cat groper"),
	_("a cat humper"),
	_("a cat molester"),
	_("a cat porker"),
	_("a cat ravisher"),
	_("a cat rooter"),
	_("a cat screwer"),
	_("a cat shafter"),
	_("a cat shagger"),
	_("a cat snogger"),
	_("a catnapper"),
	_("a caveman"),
	_("a cavewoman"),
	_("a chav"),
	_("a chicken"),
	_("a chicken fingerer"),
	_("a chicken fondler"),
	_("a chicken fucker"),
	_("a chicken groper"),
	_("a chicken humper"),
	_("a chicken molester"),
	_("a chicken porker"),
	_("a chicken ravisher"),
	_("a chicken rooter"),
	_("a chicken screwer"),
	_("a chicken shafter"),
	_("a chicken shagger"),
	_("a chicken snogger"),
	_("a child fingerer"),
	_("a child fondler"),
	_("a child fucker"),
	_("a child groper"),
	_("a child humper"),
	_("a child molester"),
	_("a child pasher"),
	_("a child porker"),
	_("a child ravisher"),
	_("a child rooter"),
	_("a child screwer"),
	_("a child seducer"),
	_("a child shafter"),
	_("a child shagger"),
	_("a child snogger"),
	_("a chit"),
	_("a choad"),
	_("a chucklehead"),
	_("a chump"),
	_("a churl"),
	_("a clit"),
	_("a clitbag"),
	_("a clithead"),
	_("a clit head"),
	_("a clit spasm"),
	_("a clod"),
	_("a clown"),
	_("a clumsy clod"),
	_("a clunge"),
	_("a cock"),
	_("a cockburger"),
	_("a cockfucker"),
	_("a cock fluffer"),
	_("a cockhead"),
	_("a cock holster"),
	_("a cock-juggling thunder cunt"),
	_("a cocknose"),
	_("a cockroach"),
	_("a cocksucker"),
	_("a cockwaddle"),
	_("a cockweasel"),
	_("a cockwomble"),
	_("a common sneak thief"),
	_("a con"),
	_("a con merchant"),
	_("a coomer"),
	_("a cootie face"),
	_("a coprophile"),
	_("a corpse fucker"),
	_("a couch potato"),
	_("a country bumpkin"),
	_("a cousin fingerer"),
	_("a cousin fondler"),
	_("a cousin fucker"),
	_("a cousin groper"),
	_("a cousin humper"),
	_("a cousin molester"),
	_("a cousin pasher"),
	_("a cousin porker"),
	_("a cousin ravisher"),
	_("a cousin rooter"),
	_("a cousin screwer"),
	_("a cousin seducer"),
	_("a cousin shafter"),
	_("a cousin shagger"),
	_("a cousin snogger"),
	_("a cow"),
	_("a coward"),
	_("a cow fingerer"),
	_("a cow fondler"),
	_("a cow fucker"),
	_("a cow groper"),
	_("a cow humper"),
	_("a cow molester"),
	_("a cow porker"),
	_("a cow ravisher"),
	_("a cow rooter"),
	_("a cow screwer"),
	_("a cow shafter"),
	_("a cow shagger"),
	_("a cow snogger"),
	_("a crab"),
	_("a crackhead"),
	_("a crack whore"),
	_("a crap eater"),
	_("a craphole"),
	_("a creep"),
	_("a creeper"),
	_("a cretin"),
	_("a crikey"),
	_("a criminal"),
	_("a crook"),
	_("a crud"),
	_("a crud head"),
	_("a crybaby"),
	_("a cuck"),
	_("a cuck fluffer"),
	_("a cuckold"),
	_("a culprit"),
	_("a cumbubble"),
	_("a cumbucket"),
	_("a cum burgler"),
	_("a cum dumpster"),
	_("a cum fucker"),
	_("a cum guzzler"),
	_("a cum licker"),
	_("a cum slut"),
	_("a cumslut"),
	_("a cum stain"),
	_("a cum wipe"),
	_("a cunt"),
	_("a cuntass"),
	_("a cunt biscuit"),
	_("a cunt bitch"),
	_("cunt-breath"),
	_("a cunt face"),
	_("a cunt fart"),
	_("a cunt fucker"),
	_("a cunt head"),
	_("a cunt licker"),
	_("a cunt muncher"),
	_("a cunt puddle"),
	_("a cunt rag"),
	_("a cunt shit"),
	_("a cut sucker"),
	_("a cunt-zilla"),
	_("cunt-zilla"),
	_("a dad fingerer"),
	_("a dad fondler"),
	_("a dad fucker"),
	_("a dad groper"),
	_("a dad humper"),
	_("a dad molester"),
	_("a dad pasher"),
	_("a dad porker"),
	_("a dad ravisher"),
	_("a dad rooter"),
	_("a dad screwer"),
	_("a dad seducer"),
	_("a dad shafter"),
	_("a dad shagger"),
	_("a dad snogger"),
	_("a daddy fingerer"),
	_("a daddy fondler"),
	_("a daddy fucker"),
	_("a daddy groper"),
	_("a daddy humper"),
	_("a daddy molester"),
	_("a daddy pasher"),
	_("a daddy porker"),
	_("a daddy ravisher"),
	_("a daddy rooter"),
	_("a daddy screwer"),
	_("a daddy seducer"),
	_("a daddy shafter"),
	_("a daddy shagger"),
	_("a daddy snogger"),
	_("a dandy prat"),
	_("a daughter fingerer"),
	_("a daughter fondler"),
	_("a daughter fucker"),
	_("a daughter groper"),
	_("a daughter humper"),
	_("a daughter molester"),
	_("a daughter pasher"),
	_("a daughter porker"),
	_("a daughter ravisher"),
	_("a daughter rooter"),
	_("a daughter screwer"),
	_("a daughter seducer"),
	_("a daughter shafter"),
	_("a daughter shagger"),
	_("a daughter snogger"),
	_("a dead head"),
	_("a Debbie Downer"),
	_("a degen"),
	_("a degenerate"),
	_("a delinquent"),
	_("a dendrophile"),
	_("a dendrophiliac"),
	_("a der-brain"),
	_("a derp"),
	_("a dick"),
	_("a dick ass"),
	_("a dick bag"),
	_("dick breath"),
	_("dick cheese"),
	_("a dick fart"),
	_("a dick fucker"),
	_("a dick girl"),
	_("a dick-head"),
	_("a dick-hole"),
	_("dickless"),
	_("a dick licker"),
	_("a dick man"),
	_("dick mouth"),
	_("a dick shitter"),
	_("a dick sniffer"),
	_("a dick-splash"),
	_("a dick sucker"),
	_("a dicktard"),
	_("dicktits"),
	_("dick-wad"),
	_("a dick-wad"),
	_("a dick weasel"),
	_("a dickweed"),
	_("a dildo"),
	_("a dill pickle"),
	_("a dim bulb"),
	_("a dimma-dumb-ass"),
	_("a dimwit"),
	_("a ding-a-ling"),
	_("a ding-dong"),
	_("a ding-head"),
	_("a dingleberry"),
	_("a dingus"),
	_("a dinosaur"),
	_("a dipfuck"),
	_("a dipshit"),
	_("a dipstick"),
	_("a dirtbag"),
	_("a dirt muncher"),
	_("a dirtwad"),
	_("a dirty hoe"),
	_("a dirty hoebag"),
	_("a dirty hooker"),
	_("a dirty-hooker fucker"),
	_("a disgrace"),
	_("a dodo"),
	_("a dog"),
	_("a dog fingerer"),
	_("a dog fondler"),
	_("a dog fucker"),
	_("a dog groper"),
	_("a dog humper"),
	_("a dog molester"),
	_("a dog porker"),
	_("a dog ravisher"),
	_("a dog rooter"),
	_("a dog screwer"),
	_("a dog shafter"),
	_("a dog shagger"),
	_("a dog snogger"),
	_("a dogbolt"),
	_("dogbreath"),
	_("a dolt"),
	_("a donkey"),
	_("a donkey dick"),
	_("a donkey fingerer"),
	_("a donkey fondler"),
	_("a donkey fucker"),
	_("a donkey groper"),
	_("a donkey humper"),
	_("a donkey molester"),
	_("a donkey porker"),
	_("a donkey ravisher"),
	_("a donkey rooter"),
	_("a donkey screwer"),
	_("a donkey shafter"),
	_("a donkey shagger"),
	_("a donkey snogger"),
	_("a donkey-hole"),
	_("a donkey's dick"),
	_("a doodle"),
	_("a doofus"),
	_("a dope"),
	_("a dope head"),
	_("a dote"),
	_("a dotterel"),
	_("a douche"),
	_("a douche bag"),
	_("a douche burger"),
	_("a douche canoe"),
	_("a douche fag"),
	_("a douche lord"),
	_("a douche narc"),
	_("a douche nozzle"),
	_("a douche mark"),
	_("a douche-wad"),
	_("a douche wagon"),
	_("a dreg"),
	_("a drip"),
	_("a drug addict"),
	_("a drug dealer"),
	_("a druggie"),
	_("a druggy"),
	_("a drunkard"),
	_("a duck fingerer"),
	_("a duck fondler"),
	_("a duck fucker"),
	_("a duck groper"),
	_("a duck humper"),
	_("a duck molester"),
	_("a duck porker"),
	_("a duck ravisher"),
	_("a duck rooter"),
	_("a duck screwer"),
	_("a duck shafter"),
	_("a duck shagger"),
	_("a duck snogger"),
	_("a dullard"),
	_("as dumb as a bag of hammers"),
	_("as dumb as a box of rocks"),
	_("a dumb-arse"),
	_("a dumbass"),
	_("a dumbbell"),
	_("a dumb blonde"),
	_("a dumb fucker"),
	_("a dumb mother fucker"),
	_("a dumbo"),
	_("a dum dum"),
	_("a dummy"),
	_("a dump"),
	_("a dump fucker"),
	_("a dump truck"),
	_("a dunce"),
	_("a dunce bucket"),
	_("a dunderhead"),
	_("a dweeb"),
	_("a dweebling"),
	_("a dweeb kisser"),
	_("a dyke"),
	_("an earthworm"),
	_("an edgelord"),
	_("an egg head"),
	_("an egotist"),
	_("an emo"),
	_("an environment pants"),
	_("an envirotard"),
	_("a eunuch"),
	_("a faggot"),
	_("fag tits"),
	_("a failed abortion"),
	_("a failure"),
	_("a fairy"),
	_("a fanny"),
	_("fanny flaps"),
	_("a fart"),
	_("fart balls"),
	_("fart boy"),
	_("a fart butt"),
	_("a farter"),
	_("a fart-arse"),
	_("a fart face"),
	_("a fart fucker"),
	_("a fart fister"),
	_("a fart head"),
	_("a fart hole"),
	_("a fart knocker"),
	_("a fart molester"),
	_("a fart ravisher"),
	_("a fart sniffer"),
	_("a fart smeller"),
	_("a fart sucker"),
	_("a fart turd"),
	_("a fascist"),
	_("fat"),
	_("a fat-arse"),
	_("a fatass"),
	_("fat face"),
	_("a fat fuck"),
	_("a fat fucker"),
	_("a fat head"),
	_("a fat licker"),
	_("a fat smudger"),
	_("a father fingerer"),
	_("a father fister"),
	_("a father fondler"),
	_("a father fucker"),
	_("a father groper"),
	_("a father humper"),
	_("a father molester"),
	_("a father pasher"),
	_("a father porker"),
	_("a father ravisher"),
	_("a father rooter"),
	_("a father screwer"),
	_("a father seducer"),
	_("a father shafter"),
	_("a father shagger"),
	_("a father snogger"),
	_("a father fucking home-wrecker"),
	_("father-less"),
	_("fatherless"),
	_("a fatso"),
	_("a fatty"),
	_("a fender-head"),
	_("a fetus"),
	_("a few beers short of a six-pack"),
	_("a few bits short of a byte"),
	_("a few boats short of a fleet"),
	_("a few Bradys short of a bunch"),
	_("a few bristles short of a broom"),
	_("a few cards short of a deck"),
	_("a few clowns short of a circus"),
	_("a few colours short of a rainbow"),
	_("a few fish short of a school"),
	_("a few fries short of a Happy Meal"),
	_("a few fruitloops shy of a bowl"),
	_("a few fuses short of a circuit"),
	_("a few keys short of a keyboard"),
	_("a few leaves short of a bush"),
	_("a few peas short of a casserole"),
	_("a few pecans short of a fruitcake"),
	_("a few sandwiches short of a picnic"),
	_("a few screws short of a hardware store"),
	_("a few sheep short of a flock"),
	_("a few snags short of a barbie"),
	_("a few tacos short of a fiesta platter"),
	_("a few threads short of a sweater"),
	_("a few toppings short of a pizza"),
	_("a few tracks short of an album"),
	_("a fibber"),
	_("filth"),
	_("filthy"),
	_("a fish fingerer"),
	_("a fish fister"),
	_("a fish fondler"),
	_("a fish fucker"),
	_("a fish groper"),
	_("a fish humper"),
	_("a fish licker"),
	_("a fish molester"),
	_("a fish porker"),
	_("a fish ravisher"),
	_("a fish rooter"),
	_("a fish screwer"),
	_("a fish shafter"),
	_("a fish shagger"),
	_("a fish snogger"),
	_("a flagpole sitter"),
	_("a flagpole fucker"),
	_("a flake"),
	_("a flat-earther"),
	_("a fleabag"),
	_("a flip-flopper"),
	_("a fly fucker"),
	_("a fool"),
	_("a foreskin"),
	_("a forty year old virgin"),
	_("four eyes"),
	_("four-eyes"),
	_("a frat-boy bitch"),
	_("a freak"),
	_("a furuitcake"),
	_("a fruit-cake"),
	_("a frump"),
	_("frumpy"),
	_("a fuck"),
	_("fuckbait"),
	_("a fuck bucket"),
	_("a fucker"),
	_("fuckface"),
	_("a fuckhead"),
	_("a fuck noggin"),
	_("a fucknose"),
	_("a fuck nozzle"),
	_("a fuck nugget"),
	_("a fuckrod"),
	_("fuckshit"),
	_("a fuck-skull"),
	_("a fuckstain"),
	_("a fucktard"),
	_("a fuck toy"),
	_("a fuck trumpet"),
	_("a fuck-weasel"),
	_("a fuckwit"),
	_("a fudge packer"),
	_("a fudge fucker"),
	_("fugly"),
	_("a fugly fucker"),
	_("a furry"),
	_("a furry fucker"),
	_("a futa"),
	_("a futanari"),
	_("a fuzz-nut"),
	_("a gaper"),
	_("a gaping arse-hole"),
	_("a gaping asshole"),
	_("garbage"),
	_("a gawker"),
	_("gay"),
	_("a gaytard"),
	_("a gaywad"),
	_("a geek"),
	_("a gimp"),
	_("a ginger"),
	_("a girl fingerer"),
	_("a girl fondler"),
	_("a girl fucker"),
	_("a girl groper"),
	_("a girl humper"),
	_("a girl molester"),
	_("a girl pasher"),
	_("a girl porker"),
	_("a girl ravisher"),
	_("a girl rooter"),
	_("a girl screwer"),
	_("a girl seducer"),
	_("a girl shafter"),
	_("a girl shagger"),
	_("a girl snogger"),
	_("a git"),
	_("a glut"),
	_("a glutton"),
	_("a glutton for punishment"),
	_("a goat fingerer"),
	_("a goat fondler"),
	_("a goat fucker"),
	_("a goat groper"),
	_("a goat humper"),
	_("a goat molester"),
	_("a goat porker"),
	_("a goat ravisher"),
	_("a goat rooter"),
	_("a goat screwer"),
	_("a goat shafter"),
	_("a goat shagger"),
	_("a goat snogger"),
	_("a goblin"),
	_("a gobshite"),
	_("a goober"),
	_("a good-for-nothing"),
	_("a good-for-nothing low-life"),
	_("a goody two-shoes"),
	_("a goontard"),
	_("a goose fingerer"),
	_("a goose fondler"),
	_("a goose fucker"),
	_("a goose groper"),
	_("a goose humper"),
	_("a goose molester"),
	_("a goose porker"),
	_("a goose ravisher"),
	_("a goose rooter"),
	_("a goose screwer"),
	_("a goose shafter"),
	_("a goose shagger"),
	_("a goose snogger"),
	_("a gorilla"),
	_("a gorilla fucker"),
	_("a grand-daddy fucker"),
	_("a grandfather fingerer"),
	_("a grandfather fister"),
	_("a grandfather fondler"),
	_("a grandfather fucker"),
	_("a grandfather groper"),
	_("a grandfather humper"),
	_("a grandfather molester"),
	_("a grandfather pasher"),
	_("a grandfather porker"),
	_("a grandfather ravisher"),
	_("a grandfather rooter"),
	_("a grandfather screwer"),
	_("a grandfather seducer"),
	_("a grandfather shafter"),
	_("a grandfather shagger"),
	_("a grandfather snogger"),
	_("a grandmother fingerer"),
	_("a grandmother fondler"),
	_("a grandmother fucker"),
	_("a grandmother groper"),
	_("a grandmother humper"),
	_("a grandmother molester"),
	_("a grandmother pasher"),
	_("a grandmother porker"),
	_("a grandmother ravisher"),
	_("a grandmother rooter"),
	_("a grandmother screwer"),
	_("a grandmother seducer"),
	_("a grandmother shafter"),
	_("a grandmother shagger"),
	_("a grandmother snogger"),
	_("a grandma fingerer"),
	_("a grandma fondler"),
	_("a grandma fucker"),
	_("a grandma groper"),
	_("a grandma humper"),
	_("a grandma molester"),
	_("a grandma pasher"),
	_("a grandma porker"),
	_("a grandma ravisher"),
	_("a grandma rooter"),
	_("a grandma screwer"),
	_("a grandma seducer"),
	_("a grandma shafter"),
	_("a grandma shagger"),
	_("a grandma snogger"),
	_("a grandpa fingerer"),
	_("a grandpa fondler"),
	_("a grandpa fucker"),
	_("a grandpa groper"),
	_("a grandpa humper"),
	_("a grandpa molester"),
	_("a grandpa pasher"),
	_("a grandpa porker"),
	_("a grandpa ravisher"),
	_("a grandpa rooter"),
	_("a grandpa screwer"),
	_("a grandpa seducer"),
	_("a grandpa shafter"),
	_("a grandpa shagger"),
	_("a grandpa snogger"),
	_("a granny fucker"),
	_("a great-grandparent fingerer"),
	_("a great-grandparent fondler"),
	_("a great-grandparent fucker"),
	_("a great-grandparent groper"),
	_("a great-grandparent humper"),
	_("a great-grandparent molester"),
	_("a great-grandparent pasher"),
	_("a great-grandparent porker"),
	_("a great-grandparent ravisher"),
	_("a great-grandparent rooter"),
	_("a great-grandparent screwer"),
	_("a great-grandparent seducer"),
	_("a great-grandparent shafter"),
	_("a great-grandparent shagger"),
	_("a great-grandparent snogger"),
	_("a grinch"),
	_("a gronk"),
	_("gronkface"),
	_("a gumby"),
	_("a gump"),
	_("a guttermouth"),
	_("hair-brained"),
	_("a hand fucker"),
	_("a hand-fucker"),
	_("a hillbilly"),
	_("a hillbilly cousin-fucker"),
	_("a hippie"),
	_("a hobo"),
	_("a hobo fucker"),
	_("a hoe"),
	_("a hoebag"),
	_("a hog fucker"),
	_("hog headed"),
	_("a homo"),
	_("a hoodlum"),
	_("a hooker"),
	_("a horn-guzzler"),
	_("a horn-swaggler"),
	_("horse-faced"),
	_("a horse fingerer"),
	_("a horse fondler"),
	_("a horse fucker"),
	_("a horse groper"),
	_("a horse humper"),
	_("a horse molester"),
	_("a horse porker"),
	_("a horse ravisher"),
	_("a horse rooter"),
	_("a horse screwer"),
	_("a horse shafter"),
	_("a horse shagger"),
	_("a horse snogger"),
	_("a horse's arse"),
	_("a horse's ass"),
	_("a human participation award"),
	_("a humper"),
	_("a hussy"),
	_("a hyena fucker"),
	_("an idiot"),
	_("an idiot sandwich"),
	_("an ignoramus"),
	_("an ignorant anus"),
	_("an imbecile"),
	_("inbred"),
	_("inbred trailer trash"),
	_("an inbred"),
	_("an inbred asshole"),
	_("an inbred hillbilly"),
	_("an inbreeder"),
	_("an incel"),
	_("an incester"),
	_("a jackass"),
	_("a jack-arse"),
	_("a jackwagon"),
	_("a jack-waggler"),
	_("a jelly belly"),
	_("a jelly roll"),
	_("a jerk"),
	_("a jerk stain"),
	_("a jerkoff"),
	_("a jerkwad"),
	_("jizzbreath"),
	_("jizz-breathed"),
	_("a jizz guzzler"),
	_("a jizz licker"),
	_("jizzpants"),
	_("a jizz stain"),
	_("a jizz wizard"),
	_("a junkie"),
	_("a Karen"),
	_("a kiddie fiddler"),
	_("a kiddy fiddler"),
	_("a kid fingerer"),
	_("a kid fondler"),
	_("a kid fucker"),
	_("a kid groper"),
	_("a kid humper"),
	_("a kid molester"),
	_("a kid porker"),
	_("a kid ravisher"),
	_("a kid rooter"),
	_("a kid screwer"),
	_("a kid shafter"),
	_("a kid shagger"),
	_("a kid snogger"),
	_("a klutz"),
	_("a knob"),
	_("a knobhead"),
	_("a knob jockey"),
	_("a knucklehead"),
	_("a lamebrain"),
	_("lame-brained"),
	_("a lamb fingerer"),
	_("a lamb fondler"),
	_("a lamb fucker"),
	_("a lamb groper"),
	_("a lamb humper"),
	_("a lamb molester"),
	_("a lamb porker"),
	_("a lamb ravisher"),
	_("a lamb rooter"),
	_("a lamb screwer"),
	_("a lamb shafter"),
	_("a lamb shagger"),
	_("a lamb snogger"),
	_("a land whale"),
	_("a lard butt"),
	_("lard-faced"),
	_("lard farts"),
	_("a lesbian"),
	_("a lesbo"),
	_("a lezbo"),
	_("a lezzo"),
	_("a lick-spittle"),
	_("a little brother fingerer"),
	_("a little brother fondler"),
	_("a little brother fucker"),
	_("a little brother groper"),
	_("a little brother humper"),
	_("a little brother molester"),
	_("a little brother pasher"),
	_("a little brother porker"),
	_("a little brother ravisher"),
	_("a little brother rooter"),
	_("a little brother screwer"),
	_("a little brother seducer"),
	_("a little brother shafter"),
	_("a little brother shagger"),
	_("a little brother snogger"),
	_("a little sister fingerer"),
	_("a little sister fister"),
	_("a little sister fondler"),
	_("a little sister fucker"),
	_("a little sister groper"),
	_("a little sister humper"),
	_("a little sister molester"),
	_("a little sister pasher"),
	_("a little sister porker"),
	_("a little sister ravisher"),
	_("a little sister rooter"),
	_("a little sister screwer"),
	_("a little sister seducer"),
	_("a little sister shafter"),
	_("a little sister shagger"),
	_("a little sister snogger"),
	_("a loaf of bread"),
	_("a loafer"),
	_("a lobotomite"),
	_("a lodge rat"),
	_("a loser"),
	_("a louse"),
	_("a louse licker"),
	_("a low-life"),
	_("a low-life inbred"),
	_("a lummox"),
	_("a lunatic"),
	_("a lunkhead"),
	_("a lurdane"),
	_("a mackerel"),
	_("a maggot"),
	_("a maggot licker"),
	_("a mamzer"),
	_("a meanie"),
	_("a meathead"),
	_("meat-headed"),
	_("a megabitch"),
	_("megabutt"),
	_("a megacunt"),
	_("a megadouche"),
	_("a megagimp"),
	_("a megagit"),
	_("a megalodon"),
	_("megasaurus"),
	_("a megashit"),
	_("a megatwat"),
	_("a midget"),
	_("a milk chugger"),
	_("a milksop"),
	_("a milkweed"),
	_("mingie"),
	_("missing link"),
	_("a mistake"),
	_("a mofo"),
	_("a mom fingerer"),
	_("a mom fondler"),
	_("a mom fucker"),
	_("a mom groper"),
	_("a mom humper"),
	_("a mom molester"),
	_("a mom pasher"),
	_("a mom porker"),
	_("a mom ravisher"),
	_("a mom rooter"),
	_("a mom screwer"),
	_("a mom seducer"),
	_("a mom shafter"),
	_("a mom shagger"),
	_("a mom snogger"),
	_("a mongoose"),
	_("a mongrel"),
	_("a monkey fingerer"),
	_("a monkey fondler"),
	_("a monkey fucker"),
	_("a monkey groper"),
	_("a monkey humper"),
	_("a monkey molester"),
	_("a monkey porker"),
	_("a monkey ravisher"),
	_("a monkey rooter"),
	_("a monkey screwer"),
	_("a monkey shafter"),
	_("a monkey shagger"),
	_("a monkey snogger"),
	_("monkey-faced"),
	_("a monkeyspank"),
	_("a monkey's cock"),
	_("a monkey's arse"),
	_("a monkey's ass"),
	_("a moron"),
	_("a motherbitch"),
	_("a mother fingerer"),
	_("a mother fondler"),
	_("a mother fucker"),
	_("a mother groper"),
	_("a mother humper"),
	_("a mother molester"),
	_("a mother pasher"),
	_("a mother porker"),
	_("a mother ravisher"),
	_("a mother rooter"),
	_("a mother screwer"),
	_("a mother seducer"),
	_("a mother shafter"),
	_("a mother shagger"),
	_("a mother snogger"),
	_("a mouse fucker"),
	_("a mouth breather"),
	_("a muff diver"),
	_("a mug"),
	_("a mule"),
	_("a mule fucker"),
	_("a mullet"),
	_("a mullet fucker"),
	_("a mum fingerer"),
	_("a mum fondler"),
	_("a mum fucker"),
	_("a mum groper"),
	_("a mum humper"),
	_("a mum molester"),
	_("a mum pasher"),
	_("a mum porker"),
	_("a mum ravisher"),
	_("a mum rooter"),
	_("a mum screwer"),
	_("a mum seducer"),
	_("a mum shafter"),
	_("a mum shagger"),
	_("a mum snogger"),
	_("a mumbler"),
	_("a mump"),
	_("a mungbean"),
	_("a muppet"),
	_("a muppet fucker"),
	_("mush-headed"),
	_("a mutant"),
	_("a mutt"),
	_("a mutt fucker"),
	_("nasty pants"),
	_("a neaderthal"),
	_("a neaderthal's fucktoy"),
	_("nebbish"),
	_("a neckbeard"),
	_("a necrophiliac"),
	_("a ne'er-do-well"),
	_("a nephew fingerer"),
	_("a nephew fondler"),
	_("a nephew fucker"),
	_("a nephew groper"),
	_("a nephew humper"),
	_("a nephew molester"),
	_("a nephew pasher"),
	_("a nephew porker"),
	_("a nephew ravisher"),
	_("a nephew rooter"),
	_("a nephew screwer"),
	_("a nephew seducer"),
	_("a nephew shafter"),
	_("a nephew shagger"),
	_("a nephew snogger"),
	_("a nerf herder"),
	_("a niece fingerer"),
	_("a niece fondler"),
	_("a niece fucker"),
	_("a niece groper"),
	_("a niece humper"),
	_("a niece molester"),
	_("a niece pasher"),
	_("a niece porker"),
	_("a niece ravisher"),
	_("a niece rooter"),
	_("a niece screwer"),
	_("a niece seducer"),
	_("a niece shafter"),
	_("a niece shagger"),
	_("a niece snogger"),
	_("a nimrod"),
	_("a nincompoop"),
	_("a ninny"),
	_("a ninnyhammer"),
	_("a nit"),
	_("a nitwit"),
	_("a nobody"),
	_("a nonce"),
	_("a noob"),
	_("a noodle"),
	_("not the brightest light in the harbour"),
	_("not the crunchies chip in the bag"),
	_("not the fastest car on the track"),
	_("not the quickest horse in the stable"),
	_("not the sharpest blade on the mower"),
	_("not the sharpest fork in the barn"),
	_("not the sharpest knife in the drawer"),
	_("not the sharpest tool in the shed"),
	_("not the tallest tree in the forest"),
	_("numbnuts"),
	_("a numbskull"),
	_("a numpty"),
	_("a nut"),
	_("a nutjob"),
	_("a nutsack"),
	_("an oaf"),
	_("an oddball"),
	_("an ogre"),
	_("an oinker"),
	_("an oompa loompa"),
	_("an orphan"),
	_("an outcast"),
	_("an oxygen thief"),
	_("a packrat"),
	_("a pain in the arse"),
	_("a pain in the ass"),
	_("a pain in the butt"),
	_("a panini head"),
	_("a pansy"),
	_("pants"),
	_("a pariah"),
	_("a parent fingerer"),
	_("a parent fondler"),
	_("a parent fucker"),
	_("a parent groper"),
	_("a parent humper"),
	_("a parent molester"),
	_("a parent pasher"),
	_("a parent porker"),
	_("a parent ravisher"),
	_("a parent rooter"),
	_("a parent screwer"),
	_("a parent seducer"),
	_("a parent shafter"),
	_("a parent shagger"),
	_("a parent snogger"),
	_("a party pooper"),
	_("a peasant"),
	_("a pedo"),
	_("a pedophile"),
	_("a peehole"),
	_("a peeping tom"),
	_("a pencil dick"),
	_("a penis butt-face"),
	_("a penis fluffer"),
	_("a penis head"),
	_("a penis licker"),
	_("a penis pasher"),
	_("a penis puffer"),
	_("a penis sucker"),
	_("a perv"),
	_("a pervert"),
	_("a pervy weirdo"),
	_("a philanderer"),
	_("a pickle-puss"),
	_("a piece of crap"),
	_("a piece of garbage"),
	_("a piece of shit"),
	_("a piece of shite"),
	_("a piece of trash"),
	_("a piece of work"),
	_("a pie hole"),
	_("a pie fucker"),
	_("a pig"),
	_("a pig farmer"),
	_("a pig fingerer"),
	_("a pig fondler"),
	_("a pig fucker"),
	_("a pig groper"),
	_("a pig humper"),
	_("a pig molester"),
	_("a pig porker"),
	_("a pig ravisher"),
	_("a pig rooter"),
	_("a pig screwer"),
	_("a pig shafter"),
	_("a pig shagger"),
	_("a pig snogger"),
	_("a piggy"),
	_("piggy-wiggy"),
	_("pig shit"),
	_("pig shite"),
	_("pig slop"),
	_("a pillock"),
	_("a pimple"),
	_("a pinhead"),
	_("a pissbrain"),
	_("piss-brained"),
	_("piss-breath"),
	_("a piss drinker"),
	_("piss-face"),
	_("piss-faced"),
	_("piss gulper"),
	_("a piss monkey"),
	_("a piss pants"),
	_("a piss pot"),
	_("a piss wizard"),
	_("a pissy baby"),
	_("a pissy bitch"),
	_("a pissy pants"),
	_("a pizzaface"),
	_("pizza-faced"),
	_("a pleb"),
	_("a plebian"),
	_("a plonker"),
	_("a poo"),
	_("a poo canoe"),
	_("a poo eater"),
	_("a poo fister"),
	_("a poo fucker"),
	_("a poo hole"),
	_("a poo head"),
	_("a poo licker"),
	_("a poo muncher"),
	_("a poo pants"),
	_("a poo saver"),
	_("a poo-face"),
	_("poo-faced"),
	_("a poo-head"),
	_("a poo-poo-head"),
	_("a poop"),
	_("a poop canoe"),
	_("a poop eater"),
	_("a poop fister"),
	_("a poop fucker"),
	_("a poop hole"),
	_("a poop head"),
	_("a poop licker"),
	_("a poop muncher"),
	_("a poop pants"),
	_("a poop saver"),
	_("a poop snogger"),
	_("a poop-face"),
	_("poop-faced"),
	_("a poop-head"),
	_("a poopy head"),
	_("a poopy pants"),
	_("a poopy poo-pants"),
	_("a potato"),
	_("a potty head"),
	_("a potty mouth"),
	_("a prat"),
	_("a pratler"),
	_("a predator"),
	_("a prick"),
	_("a prickface"),
	_("a prickhead"),
	_("a problem"),
	_("a prom night dumpster baby"),
	_("a pseudointellectual"),
	_("a psycho"),
	_("a pube"),
	_("pube face"),
	_("a pube flosser"),
	_("a pube keeper"),
	_("a pube saver"),
	_("pube pants"),
	_("a pubic hair"),
	_("a pudwhacker"),
	_("a puke"),
	_("a puke bag"),
	_("a pukeball"),
	_("puke face"),
	_("a punk"),
	_("a punkass"),
	_("a punkass bitch"),
	_("a puppet"),
	_("a pus licker"),
	_("pussy"),
	_("a pussy"),
	_("a pussy fucker"),
	_("a pussy gobbler"),
	_("a pussy kisser"),
	_("a pussy licker"),
	_("a pussy mother-fucker"),
	_("a pussy pasher"),
	_("a pussy pisser"),
	_("a pussy snogger"),
	_("a pussy sucker"),
	_("a puta"),
	_("a quack"),
	_("a queef"),
	_("a queef cookie"),
	_("queer bait"),
	_("a querulant"),
	_("a rabbit fingerer"),
	_("a rabbit fondler"),
	_("a rabbit fucker"),
	_("a rabbit groper"),
	_("a rabbit humper"),
	_("a rabbit molester"),
	_("a rabbit porker"),
	_("a rabbit ravisher"),
	_("a rabbit rooter"),
	_("a rabbit screwer"),
	_("a rabbit shafter"),
	_("a rabbit shagger"),
	_("a rabbit snogger"),
	_("a ranga"),
	_("a rat"),
	_("a rat catcher"),
	_("a rat fingerer"),
	_("a rat fondler"),
	_("a rat fucker"),
	_("a rat groper"),
	_("a rat humper"),
	_("a rat molester"),
	_("a rat porker"),
	_("a rat ravisher"),
	_("a rat rooter"),
	_("a rat screwer"),
	_("a rat shafter"),
	_("a rat shagger"),
	_("a rat snogger"),
	_("a rectal wart"),
	_("a redditor"),
	_("a redneck"),
	_("a reject"),
	_("a reprobate"),
	_("a retard"),
	_("a retard fucker"),
	_("retarded"),
	_("a robot"),
	_("a robot fucker"),
	_("a roughneck"),
	_("a ruffian"),
	_("a rug muncher"),
	_("a ruler of the weak"),
	_("a Rumpleforeskin"),
	_("Rumplestiltskin"),
	_("a runt"),
	_("a saggy fuck"),
	_("a saggy tits fucker"),
	_("a sausage massager"),
	_("a sausage masseur"),
	_("a sausage masseuse"),
	_("a scaredy-cat"),
	_("a schlub"),
	_("a schmo"),
	_("a schmuck"),
	_("a screw up"),
	_("a scrote"),
	_("a scrotum"),
	_("scrotum butt"),
	_("a scrotum face"),
	_("a scrotum licker"),
	_("a scrotum massager"),
	_("a scrotum masseur"),
	_("a scrotum masseuse"),
	_("a scrotum sucker"),
	_("a scrotum snogger"),
	_("a scrotum rubber"),
	_("scrotum tits"),
	_("a scuddle butt"),
	_("scum"),
	_("a scumbag"),
	_("scumbreath"),
	_("a scumbutt"),
	_("a scumface"),
	_("a scumfuck"),
	_("a scumhead"),
	_("a scumlord"),
	_("a scumwad"),
	_("a scummy freak"),
	_("a scummy fuck"),
	_("a scummy twat"),
	_("a scummy weirdo"),
	_("a scuzzbag"),
	_("a scuzzball"),
	_("a scuzzbucket"),
	_("a see you next Tuesday"),
	_("a serf"),
	_("a sewer rat"),
	_("a sheep fingerer"),
	_("a sheep fister"),
	_("a sheep fondler"),
	_("a sheep fucker"),
	_("a sheep groper"),
	_("a sheep humper"),
	_("a sheep molester"),
	_("a sheep porker"),
	_("a sheep ravisher"),
	_("a sheep rooter"),
	_("a sheep screwer"),
	_("a sheep shafter"),
	_("a sheep shagger"),
	_("a sheep shit"),
	_("a sheep snogger"),
	_("a sheep shit"),
	_("a shill"),
	_("a shit"),
	_("a shitass"),
	_("a shitbag"),
	_("a shitball"),
	_("a shitbrain"),
	_("shit-brained"),
	_("a shit-bum"),
	_("shit-breathed"),
	_("a shit bucket"),
	_("a shit bum"),
	_("a shit cunt"),
	_("a shit dick"),
	_("shite"),
	_("a shite cunt"),
	_("a shite face"),
	_("a shite wanker"),
	_("a shit eater"),
	_("a shit face"),
	_("a shit fingerer"),
	_("a shit fondler"),
	_("a shit fucker"),
	_("a shit groper"),
	_("a shit humper"),
	_("a shit molester"),
	_("a shit porker"),
	_("a shit ravisher"),
	_("a shit rooter"),
	_("a shit screwer"),
	_("a shit shafter"),
	_("a shit shagger"),
	_("a shit snogger"),
	_("a shit-for-brains"),
	_("a shit-fuck"),
	_("a shit-fucker"),
	_("a shit-goblin"),
	_("a shithead"),
	_("shithouse"),
	_("a shit-kicker"),
	_("a shitlord"),
	_("a shit-maggot"),
	_("a shit-magnet"),
	_("a shit-nugget"),
	_("a shit-packer"),
	_("shit pants"),
	_("a shit-picker"),
	_("a shit-pot"),
	_("a shit-pouch"),
	_("a shit puddle"),
	_("a shit-sack"),
	_("a shit shack"),
	_("a shitshow"),
	_("a shit-slinger"),
	_("a shit-smearer"),
	_("a shit-stain"),
	_("a shit-thrower"),
	_("shit tits"),
	_("a shitty titty"),
	_("a shitty titty jelly belly"),
	_("a shit-weasel"),
	_("a shrew"),
	_("a schyster"),
	_("a sibling fingerer"),
	_("a sibling fister"),
	_("a sibling fondler"),
	_("a sibling fucker"),
	_("a sibling groper"),
	_("a sibling humper"),
	_("a sibling molester"),
	_("a sibling pasher"),
	_("a sibling porker"),
	_("a sibling ravisher"),
	_("a sibling rooter"),
	_("a sibling screwer"),
	_("a sibling seducer"),
	_("a sibling shafter"),
	_("a sibling shagger"),
	_("a sibling snogger"),
	_("a simp"),
	_("a simpleton"),
	_("a sissy"),
	_("a sister fingerer"),
	_("a sister fister"),
	_("a sister fondler"),
	_("a sister fucker"),
	_("a sister groper"),
	_("a sister humper"),
	_("a sister molester"),
	_("a sister pasher"),
	_("a sister porker"),
	_("a sister ravisher"),
	_("a sister rooter"),
	_("a sister screwer"),
	_("a sister seducer"),
	_("a sister shafter"),
	_("a sister shagger"),
	_("a sister snogger"),
	_("a skank"),
	_("a skank blanket"),
	_("a skull fucker"),
	_("a skunk"),
	_("a skunk fucker"),
	_("a slacker"),
	_("a slag"),
	_("a slaphead"),
	_("a slave"),
	_("a sleaze"),
	_("a sleazebag"),
	_("a sleazeball"),
	_("a slimeface"),
	_("a slob"),
	_("a slut"),
	_("a slutbag"),
	_("a slut bag"),
	_("a slut bucket"),
	_("a slutbung"),
	_("a slut bunger"),
	_("a slut burger"),
	_("a slut biscuit"),
	_("a slut fucker"),
	_("a slutface"),
	_("a slut fungus"),
	_("smelly fingers"),
	_("smooth-brained"),
	_("a snail"),
	_("a snapper-head"),
	_("a snob"),
	_("a snot"),
	_("a snotball"),
	_("snot-faced"),
	_("a snothead"),
	_("a snot nose"),
	_("a snot-wad"),
	_("a snowflake"),
	_("a sob"),
	_("soft-headed"),
	_("a soggy biscuit"),
	_("a son fingerer"),
	_("a son fondler"),
	_("a son fucker"),
	_("a son groper"),
	_("a son humper"),
	_("a son molester"),
	_("a son pasher"),
	_("a son porker"),
	_("a son ravisher"),
	_("a son rooter"),
	_("a son screwer"),
	_("a son seducer"),
	_("a son shafter"),
	_("a son shagger"),
	_("a son snogger"),
	_("a son of a biscuit"),
	_("a son of a bitch"),
	_("a son of a bucket"),
	_("a son of a monkey"),
	_("a son of a motherless goat"),
	_("a son of a mother fucker"),
	_("a son of a mother trucker"),
	_("a son of sea-cook"),
	_("a son of a whore"),
	_("a sow"),
	_("a soy boy"),
	_("a sphincter"),
	_("a spider fucker"),
	_("a square"),
	_("a squib"),
	_("a stick in the mud"),
	_("a stinker"),
	_("a stink hole"),
	_("stinky"),
	_("a stinky McPoop-pants"),
	_("a stupid-head"),
	_("a swine"),
	_("a swine fucker"),
	_("a tard"),
	_("a tart"),
	_("thick-headed"),
	_("a thot"),
	_("a thot pocket"),
	_("a thundercunt"),
	_("a tit"),
	_("a titbag"),
	_("a tithead"),
	_("a titty burger"),
	_("titty burgers"),
	_("a titty burgler"),
	_("a titty jelly belly"),
	_("a toad"),
	_("a tadger"),
	_("a todger"),
	_("a toe eyed cabbage"),
	_("a toenail"),
	_("a toilet baby"),
	_("a tomato"),
	_("a tool"),
	_("a tosser"),
	_("a tosspot"),
	_("trailer trash"),
	_("a tramp"),
	_("a tranny"),
	_("trash"),
	_("a tree fucker"),
	_("a troglodyte"),
	_("a troll"),
	_("troll-faced"),
	_("a trollface"),
	_("a tub of butter"),
	_("a tub of cookies"),
	_("a tub of ice-cream"),
	_("a tub of lard"),
	_("a turd"),
	_("a turd-ball"),
	_("a turd-bucket"),
	_("a turd burger"),
	_("a turd burgler"),
	_("a turd cutter"),
	_("a turd fingerer"),
	_("a turd fucker"),
	_("a turd hound"),
	_("a turd licker"),
	_("a turdpile"),
	_("a turd slinger"),
	_("a turkey"),
	_("a turkey fingerer"),
	_("a turkey fondler"),
	_("a turkey fucker"),
	_("a turkey groper"),
	_("a turkey humper"),
	_("a turkey molester"),
	_("a turkey porker"),
	_("a turkey ravisher"),
	_("a turkey rooter"),
	_("a turkey screwer"),
	_("a turkey shafter"),
	_("a turkey shagger"),
	_("a turkey snogger"),
	_("a twat"),
	_("a twatface"),
	_("twat-faced"),
	_("a twattock"),
	_("a twatwaffle"),
	_("a twerp"),
	_("a twit"),
	_("a tire-biter"),
	_("a tyre-biter"),
	_("ugly"),
	_("ugly face"),
	_("ugly-faced"),
	_("an uncle boffer"),
	_("an uncle bonker"),
	_("an uncle fingerer"),
	_("an uncle fondler"),
	_("an uncle fucker"),
	_("an uncle groper"),
	_("an uncle humper"),
	_("an uncle pasher"),
	_("an uncle porker"),
	_("an uncle ravisher"),
	_("an uncle rooter"),
	_("an uncle screwer"),
	_("an uncle seducer"),
	_("an uncle shafter"),
	_("an uncle shagger"),
	_("an uncle snogger"),
	_("an underperson"),
	_("an unseasoned cabbage"),
	_("an urchin"),
	_("a vagina cleaner"),
	_("a vaginal belch"),
	_("a vaginal bleach"),
	_("a vaginal discharge"),
	_("vaginal discharge"),
	_("a varmint"),
	_("a vegetable"),
	_("vermin"),
	_("a wacko"),
	_("a wallflower"),
	_("a wally"),
	_("a wanker"),
	_("a wankface"),
	_("wank-faced"),
	_("a wank stain"),
	_("wank-stained"),
	_("a wart"),
	_("a waste"),
	_("a waste of oxygen"),
	_("a weakling"),
	_("a weasel"),
	_("a weeaboo"),
	_("a weeb"),
	_("a weed"),
	_("a weeze-bag"),
	_("a weirdo"),
	_("wet"),
	_("a whore"),
	_("a whore bag"),
	_("a whore fucker"),
	_("a whore kisser"),
	_("a whore licker"),
	_("a whoreson"),
	_("a willy"),
	_("a wimp"),
	_("a wind fucker"),
	_("a window licker"),
	_("a wind sucker"),
	_("a woketard"),
	_("a worm"),
	_("a wretch"),
	_("a wretched person"),
	_("a wuss"),
	_("wussy"),
	_("a yampy"),
	_("a yeti"),
	_("your parents' cum dump"),
	_("yuck"),
	_("a zitface"),
	_("zit-faced"),
	_("a zoophile"),
]
