import os as _os

DEBUG = False

MALE_NAMES = open("assets/male_names.txt").read().splitlines()
FEMALE_NAMES = open("assets/female_names.txt").read().splitlines()
LAST_NAMES = open("assets/last_names.txt").read().splitlines()

SAVE_PATH = filename = _os.getcwd() + "/game_saves"  # + "/gamedata.pickle"

SALARY_TAX_BRACKETS = [
    [9950, 0.1],
    [40525, 0.12],
    [86375, 0.22],
    [164925, 0.24],
    [209425, 0.32],
    [523600, 0.35],
    0.37,
]

from src.lifesim_lib.translation import _

ILLNESSES_TRANSLATIONS = {
	"Depression": _("Depression"),
	"High Blood Pressure": _("High Blood Pressure"),
}

COMPLIMENTS = [
	_("a bubbly personality"),
	_("a champion"),
	_("a gem"),
	_("a genius"),
	_("a jewel"),
	_("a legend"),
	_("a player"),
	_("a revolutionary"),
	_("a smart cookie"),
	_("a treasure"),
	_("a winner"),
	_("a wizard"),
	_("a visionary"),
	_("adorable"),
	_("admirable"),
	_("an OG"),
	_("brave"),
	_("bright"),
	_("brilliant"),
	_("charming"),
	_("clever"),
	_("cool"),
	_("courageous"),
	_("delightful"),
	_("dope"),
	_("elite"),
	_("fascinating"),
	_("fearless"),
	_("fresh"),
	_("gorgeous"),
	_("golden"),
	_("groovy"),
	_("inspiring"),
	_("intelligent"),
	_("magnificent"),
	_("motivating"),
	_("neat"),
	_("nifty"),
	_("one-of-a-kind"),
	_("a perfect 10"),
	_("phenomenal"),
	_("rad"),
	_("smart"),
	_("spectatular"),
	_("stellar"),
	_("strong"),
	_("stunning"),
	_("stylish"),
	_("swell"),
	_("the best"),
	_("the greatest"),
	_("the life of the party"),
	_("unparalled"),
	_("wise"),
	_("wonderful")
]

CHATS = [
	_("the hierarchy of licorice"),
]
DISCUSSIONS = [
	_("why cats are better than dogs"),
	_("why dogs are better than cats"),
	_("the Russia-Ukraine War"),
	_("High Fuel Prices"),
	_("the Metaverse"),
	_("the Economic crisis of Sri Lanka"),
	_("Moonlighting"),
	_("the Pros and Cons of working from home"),
	_("whether people should invest in cryptocurrency"),
	_("the Biomedical waste crisis"),
	_("the impact of 5G on the global economy"),
	_("how to prevent the next pandemic"),
	_("the impact of COVID-19 on the global economy"),
	_("the pros and cons of block chain technology"),
	_("the role of social media in international politics"),
	_("how to end the threat of nuclear war"),
	_("the impact of COVID-19 on the education sector"),
	_("Taliban rule in Afghanistan"),
	_("the rise of the gig economy"),
	_("the harms of passive smoking"),
	_("the advantages and disadvantages of having a credit card"),
	_("whether software should be free for everyone"),
	_("whether gambling should be allowed from the age of 16"),
	_("problems caused by the economic boycott in Cuba"),
	_("how international trade barriers work"),
	_("how the United Nations is based on diplomacy and strengthening relationships"),
	_("whether or not public schools are safe enough"),
	_("whether it is necessary to hold value in what you argue"),
	_("why drink driving is dangerous"),
	_("how India became such a large milk producer"),
	_("how to make money with recycling"),
	_("the decreasing productivity of the Japanese workforce"),
	_("a business model to help health-conscious customers"),
	_("what the best technologies are to safeguard the right of free speech on the internet"),
	_("what the best technologies are to safeguard the right of privacy on the internet"),
	_("how to check for the signs of burnout"),
	_("how to overcome the coal crisis in India"),
	_("the causes of bullying in schools"),
	_("why we should have a minimum wage"),
	_("whether universal basic income is a good idea"),
	_("the leadership changes needed in our country"),
	_("whether empowering women is the solution to violence against women"),
	_("the effects of communalism on social cohesion"),
	_("whether we're becoming too sensitive in society"),
	_("lessons for the world from the COVID-19 pandemic"),
	_("whether crime rates increase because of unemployment"),
	_("causes of poverty around the world"),
	_("the effects of the Internet of Things on our lives"),
	_("whether drug abuse is rampant among teenagers"),
	_("whether anemia effects urban society"),
	_("gender equality in the workplace"),
	_("whether the wealthy should be taxed more"),
	_("whether the poor should be given more assistance"),
	_("whether it is possible to maintain a work-life balance"),
	_("whether saying 'women make good managers' is sexist like saying 'asians are good at maths' is racist"),
	_("whether job creators are needed more than job seekers"),
	_("whether a borderless world is a myth or a reality"),
	_("what would happen if Bitcoin crashed to zero and whether it is possible"),
	_("business ethics in today's market compared with the past and the potential future"),
	_("whether patience is important in business and management"),
	_("whether the family-run business is relevant in today's market"),
	_("whether E-commerce discounts are harmful in the long run and is it the business or customer being harmed"),
	_("whether globalisation is an opportunity or a threat"),
	_("how markets are found and not created"),
	_("whether the world is ready for a cashless society"),
	_("whether physical infrastructure is the answer to social equality"),
	_("whether the public sector being a guarantor of job security is a myth"),
	_("whether a circular economy is key to sustainable development"),
	_("the contribution of the Indian IT industry to the US and global economy"),
	_("whether democracy is a hindrance to economic reforms in India"),
	_("the technology behind Zero Budget Natural Farming"),
	_("the effects of technological change on jobs"),
	_("whether pervasive technology is creating a generation of cyber zombies"),
	_("whether the IT industry will create more or less jobs in the future"),
	_("whether artificial intelligence can replace human intelligence"),
	_("the effects of big data on information privacy"),
	_("whether automation will create more or less jobs"),
	_("the benefits and challenges of data localisation"),
	_("whether artifical intelligence will change the future"),
	_("how technology can be used to tackle financial crimes"),
	_("whether polythene bags should be completely banned"),
	_("how to control air pollution levels"),
	_("whether green jobs are essential for sustainable development"),
	_("how to manage natural disasters"),
	_("how to manage financial disasters"),
	_("methods of disaster recovery"),
	_("the effects of Coronaviruses on the environment"),
	_("whether smart farming is the future of agriculture"),
	_("whether genetic engineering in agriculture is good or bad"),
	_("the effects of climate on the farming system and food supply"),
	_("whether automation in farming is good"),
	_("whether collective farming is a boon or a bane"),
	_("our views on natural versus factory farming"),
	_("our views on conventional farming and organic farming"),
	_("the role of women in agriculture"),
	_("whether agroforestry destroys the environment"),
	_("gay marriage and your views on it"),
	_("whether war is the best option to solve international disputes"),
	_("whether primary school children should be allowed to own mobile phones"),
	_("whether using animals for medical research should be allowed"),
	_("whether men and women will ever be equal, if they already are, and whether equality will last"),
	_("whether you can have a happy family life and a successful career at the same time"),
	_("whether marriage is an outdated institution"),
	_("whether citizens should be allowed to carry guns and other weapons"),
	_("whether the death penalty is acceptable for any reasons"),
	_("whether non-citizens and tourists should be allowed to vote in their country of residence"),
	_("whether sex education should be taught to children under 12"),
	_("whether or not women are paid the same as men"),
	_("whether bribery and corruption is acceptable in government"),
	_("whether bribery and corruption is acceptable in private business"),
	_("whether music that glorifies violence should be banned"),
	_("whether condoms should be distributed for free in primary schools"),
	_("whether nuclear weapons are necessary weapons"),
	_("whether teachers should be allowed to carry guns"),
	_("whether professional sports people earn too much money"),
	_("our views on whether or not beauty contests should be banned"),
	_("our views on whether or not cosmetic surgery should be outlawed"),
	_("our views on whether or not abortions are okay"),
	_("our views on whether or not social deprivation causes crime"),
	_("our views on whether or not military service should be compulsory"),
	_("our views on whether or not war is ever an option for solving international disputes"),
	_("our views on whether or not torture can be acceptable in some cases"),
	_("our views on whether or not curfews keep teens out of trouble"),
	_("our views on whether or not we're becoming too dependent on computers"),
	_("our views on whether or not smoking should be banned worldwide"),
	_("our views on whether or not it should be illegal to ride a bicycle without a helmet"),
	_("our views on whether or not single sex schools are bad for childhood development and lead to unhealthy views of the opposite sex"),
	_("our views on whether or not homework is harmful"),
	_("our views on whether or not the United Nations is a failed organisation"),
	_("our views on whether or not intelligence tests should be given before couples can have children"),
	_("our views on whether or not a woman's place is in the home"),
	_("our views on whether or not it's a man's world"),
	_("our views on whether or not money makes you happy"),
	_("our views on whether or not money can buy you happiness"),
	_("our views on whether or not the internet must be censored to protect society"),
	_("our views on whether or not genetically modified foods have no ill health effects"),
	_("our views on whether a man should have a wife for the family and a paramour for pleasure"),
	_("our views on whether a woman should have a husband for the family and a paramour for pleasure"),
	_("our views on whether soft drugs should be legalised"),
	_("our views on whether or not electric cars help the environment"),
	_("our views on whether or not staying unmarried leads to a happier life"),
	_("our views on whether or not software piracy is a real crime"),
	_("our views on whether or not religion is needed"),
	_("our views on whether veganism is the key to solving climate change"),
	_("our views on whether the police force is institutionally racist"),
	_("our views on whether democracy must be imposed on nations"),
	_("our views on whether the war in Iraq was justified"),
	_("our views on whether your race affects your intelligence"),
	_("our views on whether your race affects your sporting ability"),
	_("our views on whether the world is over populated and steps must be taken to reduce births"),
	_("whether or not euthanasia should be illegal"),
	_("whether or not cloning is a valuable scientific pursuit"),
	_("whether obesity is a disease and not a lifestyle choice"),
	_("whether or not video games contribute to youth violence"),
	_("whether the drinking age should be lowered"),
	_("whether the drinking age should be raised"),
	_("whether the smoking age should be lowered"),
	_("whether the smoking age should be raised"),
	_("whether the age of consent should be lowered"),
	_("whether the age of consent should be raised"),
	_("whether the voting age should be lowered"),
	_("whether the voting age should be raised"),
	_("whether the driving age should be lowered"),
	_("whether the driving age should be raised"),
	_("whether the gambling age should be lowered"),
	_("whether the gambling age should be raised"),
	_("whether the military service age should be lowered"),
	_("whether the military service age should be raised"),
	_("whether drugs should be accepted in sports"),
	_("whether self driving cars are going to make our lives easier"),
	_("whether climate change exists"),
	_("whether carbohydrates are more damaging than fats"),
	_("whether terrorism can be justifed"),
	_("whether or not street prostitution should be illegal"),
	_("whether or not prostitution in a brothel should be illegal"),
	_("whether or not prostituting yourself in your own home should be illegal"),
	_("whether prisoners should be allowed to vote"),
	_("whether prenuptual agreements make families stronger"),
	_("whether corporal punishment should be allowed in schools"),
]
TALKS = [
	_("who will win the Monaco Grand Prix"),
]
HEART_TO_HEARTS = [
	_("the best gift you ever received"),
	_("your most bizarre pet peeves"),
	_("why you love your closest friends"),
	_("your favourite books to read at the beach"),
	_("your favourite foods to eat on a cold night"),
	_("your biggest turn offs in other people"),
	_("remembering the times when you've felt closest together"),
	_("what you would do if you knew you couldn't fail"),
	_("your favourite summertime memory"),
	_("something you've always wanted to try"),
	_("things you've always wanted to try"),
	_("a moment in history you would have liked to have been a part of"),
	_("how to manage money better"),
	_("where you would go if you could time travel"),
	_("what superpower you would have if you could have one"),
	_("what you're feeling thankful for today"),
	_("how much they mean to you"),
	_("something that you know you don't need but you're really grateful you have"),
	_("your fears of not accomplishing your New Year resolutions"),
	_("how silly New Year's resolutions are"),
	_("the best part of your day"),
	
]
